import os
import stat
import sys

from .atomic import atomic_write_text


MARKER = "Generated by lifetxt git-hook install"


def cmd_git_hook(args):
    if args.git_hook_command == "install":
        return install_hooks(args)
    if args.git_hook_command == "uninstall":
        return uninstall_hooks(args)
    if args.git_hook_command == "status":
        return status_hooks(args)
    raise ValueError("git-hook requires install, uninstall, or status.")


def install_hooks(args):
    hooks_dir = _hooks_dir(args.repo_dir)
    files = _hook_files(args)
    pre_commit = _pre_commit_script(files)
    _write_hook(os.path.join(hooks_dir, "pre-commit"), pre_commit, args.force)
    if not args.no_commit_msg:
        commit_msg = _commit_msg_script(files)
        _write_hook(os.path.join(hooks_dir, "commit-msg"), commit_msg, args.force)
    sys.stdout.write("Installed lifetxt git hooks in %s\n" % hooks_dir)
    return 0


def uninstall_hooks(args):
    hooks_dir = _hooks_dir(args.repo_dir)
    removed = []
    for name in ("pre-commit", "commit-msg"):
        path = os.path.join(hooks_dir, name)
        if not os.path.exists(path):
            continue
        if not _is_lifetxt_hook(path):
            raise ValueError(
                "%s is not a lifetxt hook; remove it manually if needed." % path
            )
        os.remove(path)
        removed.append(name)
    if removed:
        sys.stdout.write("Removed lifetxt hooks: %s\n" % ", ".join(removed))
    else:
        sys.stdout.write("No lifetxt hooks installed.\n")
    return 0


def status_hooks(args):
    hooks_dir = _hooks_dir(args.repo_dir)
    sys.stdout.write("Git hooks status (%s)\n" % hooks_dir)
    for name in ("pre-commit", "commit-msg"):
        path = os.path.join(hooks_dir, name)
        if _is_lifetxt_hook(path):
            state = "installed (lifetxt)"
        elif os.path.exists(path):
            state = "installed (non-lifetxt)"
        else:
            state = "missing"
        sys.stdout.write("  %-12s %s\n" % (name, state))
    sys.stdout.write("\nChecking files: %s\n" % " ".join(_hook_files(args)))
    return 0


def _hooks_dir(repo_dir):
    root = os.path.abspath(repo_dir or os.getcwd())
    hooks = os.path.join(root, ".git", "hooks")
    if not os.path.isdir(hooks):
        raise ValueError(
            "%s does not exist. Run this inside a Git repository or pass --repo-dir."
            % hooks
        )
    return hooks


def _hook_files(args):
    files = list(getattr(args, "files", None) or [])
    if files:
        return files
    config = getattr(args, "config_data", None) or {}
    configured = config.get("paths")
    if isinstance(configured, str):
        return [configured]
    if isinstance(configured, (list, tuple)) and configured:
        return [str(path) for path in configured]
    return ["life.txt"]


def _write_hook(path, text, force=False):
    if os.path.exists(path) and not _is_lifetxt_hook(path) and not force:
        raise ValueError(
            "%s already exists and was not generated by lifetxt. "
            "Back it up manually or rerun with --force." % path
        )
    atomic_write_text(path, text)
    mode = os.stat(path).st_mode
    os.chmod(path, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _is_lifetxt_hook(path):
    if not os.path.exists(path):
        return False
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            head = handle.read(512)
    except OSError:
        return False
    return MARKER in head


def _quote_sh(value):
    return "'" + str(value).replace("'", "'\"'\"'") + "'"


def _files_sh(files):
    return " ".join(_quote_sh(path) for path in files)


def _pre_commit_script(files):
    return """#!/bin/sh
# %s
lifetxt check %s
if [ $? -ne 0 ]; then
  echo "lifetxt check failed. Commit aborted."
  exit 1
fi
""" % (MARKER, _files_sh(files))


def _commit_msg_script(files):
    files_text = _files_sh(files)
    return """#!/bin/sh
# %s
# Append completed tasks since last commit to commit message.
SINCE=$(git log -1 --format=%%ci 2>/dev/null || echo '1970-01-01')
COMPLETED=$(lifetxt filter %s --status done --after "$SINCE" --format life 2>/dev/null)
if [ -n "$COMPLETED" ]; then
  echo "" >> "$1"
  echo "Completed tasks:" >> "$1"
  echo "$COMPLETED" | head -20 >> "$1"
fi
""" % (MARKER, files_text)
