"""Bounded server-report deployment operation for an already-running deployment.

`lifetxt server-report plan|install|remove NAME --config PATH` installs or
removes exactly one systemd oneshot+timer pair referencing an already
configured, already-validated named report profile in an existing
application config, without re-running `server-init`, without replacing any
other deployment artifact, and without creating or editing the report
profile itself (the profile must already exist and pass the authoritative
Report v2 validator).

Reuses :func:`lifetxt.server_init.report_service_unit_text` /
:func:`lifetxt.server_init.report_timer_unit_text` -- the exact same unit
generator `server-init`'s own opt-in `reporting` section (#610) uses -- so a
report job's unit content never has a second implementation regardless of
which command installed it.
"""

from __future__ import annotations

import os
from collections import OrderedDict

from . import report_cli, server_update
from .server_init import (
    ServerInitError,
    _classify_path,
    _validate_required_absolute_nowhitespace_path,
    report_service_unit_text,
    report_timer_unit_text,
)

_GENERATED_MARKER = "# Generated by lifetxt for scheduled report job"


class ServerReportError(Exception):
    def __init__(self, message, step="server_report"):
        super().__init__(message)
        self.step = step


def load_application_config(path):
    import json

    try:
        with open(path, "r", encoding="utf-8") as handle:
            data = json.load(handle)
    except OSError as exc:
        raise ServerReportError("Cannot read application config %s: %s" % (path, exc))
    except ValueError as exc:
        raise ServerReportError(
            "Application config %s is not valid JSON: %s" % (path, exc)
        )
    if not isinstance(data, dict):
        raise ServerReportError(
            "Application config %s must contain a JSON object at the top level." % path
        )
    return data


def validated_profile(app_config, name, config_path):
    """Return the validated report profile ``name``, never creating one.

    Delegates entirely to :func:`lifetxt.report_cli._profiles`, the same
    validator ``lifetxt report`` itself runs; this function adds no
    additional profile semantics of its own.
    """
    reports = app_config.get("reports")
    if not isinstance(reports, dict) or name not in reports:
        raise ServerReportError(
            "Report profile %r is not defined in %s. Add it to the application "
            "config's `reports` section first -- server-report does not create "
            "or edit report profiles." % (name, config_path)
        )
    try:
        validated = report_cli._profiles({"reports": {name: reports[name]}})
    except ValueError as exc:
        raise ServerReportError(
            "Report profile %r in %s failed validation: %s" % (name, config_path, exc)
        )
    return validated[name]


def _validate_environment_file_path(value, config_path):
    """Path-safety-validate an ``--environment-file`` value (#617).

    Reuses server_init's own absolute/no-whitespace/no-control-character
    path validator unmodified, rather than a second implementation of the
    same systemd EnvironmentFile= injection-safety check, translating its
    ServerInitError into this module's own ServerReportError.
    """
    try:
        _validate_required_absolute_nowhitespace_path(
            value, "--environment-file", config_path
        )
    except ServerInitError as exc:
        raise ServerReportError(str(exc))


def _unit_config(job_name, config_path, service_user, service_group, data_root, python):
    resolved_data_root = data_root or os.path.dirname(os.path.abspath(config_path))
    return {
        "service_user": service_user,
        "service_group": service_group,
        "data_root": resolved_data_root,
        "python": python,
        "application_config_path": os.path.abspath(config_path),
    }


def _unit_paths(unit_dir, job_name):
    service_path = os.path.join(unit_dir, "lifetxt-report-%s.service" % job_name)
    timer_path = os.path.join(unit_dir, "lifetxt-report-%s.timer" % job_name)
    return service_path, timer_path


def build_plan(
    profile_name,
    config_path,
    service_user,
    service_group,
    data_root=None,
    python=None,
    unit_dir=None,
    schedule_at="00:10",
    send_email=False,
    environment_file=None,
):
    """Build the two-file plan for one report job's systemd units.

    Never writes anything; the caller decides whether to :func:`apply_plan`
    (``install``) or discard the plan (``plan``, a dry-run preview).

    ``send_email``/``environment_file`` (#617) opt one job into scheduled
    email delivery: the profile must already carry a valid `email` section
    (checked through the same authoritative Report validator
    :func:`validated_profile` already runs -- never duplicated here), and
    ``environment_file`` is path-safety-validated before it ever reaches
    generated unit text. Neither adds a second SMTP implementation; both
    flow straight into :func:`lifetxt.server_init.report_service_unit_text`,
    the one shared unit generator ``server-init``'s own opt-in ``reporting``
    section also uses.
    """
    app_config = load_application_config(config_path)
    profile = validated_profile(app_config, profile_name, config_path)
    if send_email:
        if not profile.get("email"):
            raise ServerReportError(
                "Report profile %r has no `email` configuration; --send-email "
                "requires one, validated the same way `report send` requires "
                "it." % profile_name
            )
        if not environment_file:
            raise ServerReportError(
                "--send-email requires --environment-file PATH (an explicit "
                "EnvironmentFile= path for SMTP credentials)."
            )
        _validate_environment_file_path(environment_file, config_path)
    elif environment_file is not None:
        raise ServerReportError("--environment-file requires --send-email.")

    unit_config = _unit_config(
        profile_name, config_path, service_user, service_group, data_root, python
    )
    resolved_unit_dir = unit_dir or os.path.join(unit_config["data_root"], "systemd")
    job = {
        "name": profile_name,
        "profile": profile_name,
        "at": schedule_at,
        "send_email": send_email,
        "environment_file": environment_file,
    }
    service_path, timer_path = _unit_paths(resolved_unit_dir, profile_name)

    steps = [
        {
            "kind": "file",
            "path": service_path,
            "mode": "0644",
            "content": report_service_unit_text(unit_config, job),
        },
        {
            "kind": "file",
            "path": timer_path,
            "mode": "0644",
            "content": report_timer_unit_text(job, profile["period"]),
        },
    ]
    plan = OrderedDict(
        [
            ("status", "planned"),
            ("profile", profile_name),
            ("unit_name", "lifetxt-report-%s" % profile_name),
            ("send_email", send_email),
            ("environment_file", environment_file),
            ("steps", steps),
        ]
    )
    for step in steps:
        step["action"] = _classify_path(step)
    plan["conflicts"] = [s["path"] for s in steps if s["action"] == "conflict"]
    return plan


def apply_install(plan, service_command=None, enable=False, start=False, timeout=30):
    """Write the planned unit files and optionally enable/start the timer."""
    if plan.get("conflicts"):
        raise ServerReportError(
            "Refusing to install: existing unit file(s) differ: %s"
            % ", ".join(plan["conflicts"]),
            step="preflight",
        )
    from .server_init import _apply_file

    written = []
    for step in plan["steps"]:
        if step["action"] != "no-op":
            _apply_file(step)
        written.append(step["path"])

    commands = []
    service_command = list(service_command or ["systemctl"])
    if enable or start:
        argv = service_command + ["enable"]
        if start:
            argv.append("--now")
        argv.append("%s.timer" % plan["unit_name"])
        result = server_update._run(argv, step="server_report:enable", timeout=timeout)
        commands.append({"argv": argv, "returncode": result.returncode})
        if result.returncode != 0:
            raise ServerReportError(
                "Enabling %s.timer failed: %s"
                % (plan["unit_name"], (result.stderr or result.stdout or "").strip()),
                step="enable",
            )
    return {
        "status": "installed",
        "written": written,
        "commands": commands,
        "send_email": plan["send_email"],
        "environment_file": plan["environment_file"],
    }


def build_remove_plan(profile_name, unit_dir):
    service_path, timer_path = _unit_paths(unit_dir, profile_name)
    return OrderedDict(
        [
            ("status", "planned"),
            ("unit_name", "lifetxt-report-%s" % profile_name),
            ("paths", [service_path, timer_path]),
        ]
    )


def apply_remove(plan, service_command=None, timeout=30):
    """Best-effort disable/stop the timer, then delete only lifetxt-generated
    unit files (never a same-named file that lacks our generator marker)."""
    service_command = list(service_command or ["systemctl"])
    commands = []
    argv = service_command + ["disable", "--now", "%s.timer" % plan["unit_name"]]
    try:
        result = server_update._run(argv, step="server_report:disable", timeout=timeout)
        commands.append({"argv": argv, "returncode": result.returncode})
    except server_update.ServerUpdateError:
        # Best-effort: the unit may never have been enabled, or systemctl may
        # be unavailable in this environment (e.g. under test). Removal of
        # the unit files themselves still proceeds.
        pass

    removed = []
    skipped = []
    for path in plan["paths"]:
        if not os.path.exists(path):
            continue
        with open(path, "r", encoding="utf-8") as handle:
            content = handle.read()
        if _GENERATED_MARKER not in content:
            skipped.append(path)
            continue
        os.unlink(path)
        removed.append(path)
    return {
        "status": "removed",
        "removed": removed,
        "skipped": skipped,
        "commands": commands,
    }
