(() => {
  "use strict";
  const copy={en:{skip:"Skip to Planner",web:"Full Web UI",eyebrow:"Your day, in one place",title:"Day Planner",today:"Today",choose:"Choose date",schedule:"Schedule",tasks:"Tasks",habits:"Habits",notes:"Notes",journal:"Journal",newNote:"＋ Add a note",writeJournal:"Write today's journal",capture:"＋ Quick Capture",prompt:"What do you want to remember?",submitCapture:"Capture",labelTitle:"Title",labelBody:"Details / journal",save:"Save",close:"Close",empty:"Nothing here for this day.",done:"Mark done",saved:"Saved.",captured:"Captured.",readonly:"This workspace is read-only. Changes are disabled.",loading:"Loading…",error:"Could not load this day: ",captureError:"Capture failed: ",saveError:"Could not save: ",journalRequired:"Enter journal text before saving."},ja:{skip:"Plannerへ移動",web:"Web UI全体",eyebrow:"今日をひとつの画面に",title:"デイリープランナー",today:"今日",choose:"日付を選ぶ",schedule:"予定",tasks:"タスク",habits:"習慣",notes:"メモ",journal:"日誌",newNote:"＋ メモを追加",writeJournal:"今日の日誌を書く",capture:"＋ クイックキャプチャ",prompt:"覚えておきたいことは何ですか？",submitCapture:"記録",labelTitle:"タイトル",labelBody:"詳細 / 日誌",save:"保存",close:"閉じる",empty:"この日の記録はありません。",done:"完了を記録",saved:"保存しました。",captured:"記録しました。",readonly:"このworkspaceは読み取り専用です。変更できません。",loading:"読み込み中…",error:"この日の内容を読み込めませんでした：",captureError:"記録できませんでした：",saveError:"保存できませんでした：",journalRequired:"日誌の内容を入力してください。"}};
  const $=id=>document.getElementById(id), params=new URLSearchParams(location.search);
  let lang=params.get("lang")==="ja"?"ja":((navigator.language||"en").slice(0,2)==="ja"?"ja":"en"), t=copy.en, today="", date="", writable=false, edit=null, pending=false;
  function translate(){t=copy[lang];document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(n=>n.textContent=t[n.dataset.i18n]||n.textContent);document.title=t.title+" · life.txt"}
  async function api(path,options={}){const r=await fetch(path,options);const raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw Error(d.message||d.detail||"Request failed");return d}
  const vals=(item,key)=>Array.isArray(item?.details?.[key])?item.details[key]:item?.details?.[key]?[item.details[key]]:[];
  const pathFor=i=>i.id?"/api/items/id/"+encodeURIComponent(i.id):i.line&&i.editable?"/api/items/"+encodeURIComponent(i.line):null;
  function card(target,title,meta,action,label){const n=document.createElement("article");n.className="card";const main=document.createElement("div"),strong=document.createElement("strong");strong.textContent=title||"";main.append(strong);if(meta){const p=document.createElement("p");p.textContent=meta;main.append(p)}n.append(main);if(action){const b=document.createElement("button");b.type="button";b.textContent=label;b.addEventListener("click",action);n.append(b)}target.append(n)}
  function list(target,items,render){target.replaceChildren();if(!items.length){const p=document.createElement("p");p.className="empty";p.textContent=t.empty;target.append(p);return}items.forEach(x=>render(x))}
  async function load(){if(!date)return;$('date').value=date;const u=new URL(location.href);date===today?u.searchParams.delete("date"):u.searchParams.set("date",date);lang==="en"?u.searchParams.delete("lang"):u.searchParams.set("lang",lang);history.replaceState({},"",u.pathname+u.search);$('feedback').textContent=t.loading;
    try{const [day,agenda,habits,notes,journals,tasks]=await Promise.all([api('/api/command-center?date='+date),api('/api/agenda?from='+date+'&to='+date),api('/api/items?type=H&open_only=true'),api('/api/items?type=N&limit=20'),api('/api/items?type=J'),api('/api/items?type=T&open_only=true')]);
      list($('schedule'),(agenda.records||[]).filter(x=>["E","R","D"].includes(x.type)),x=>card($('schedule'),x.title,[x.when,x.status].filter(Boolean).join(' · ')));
      const refs=[...(day.due_today||[]),...(date===today?(day.next_actions||[]):[])].filter(x=>x.kind==="T"&&!x.blocked);const rows=(tasks.items||[]).filter(i=>refs.some(r=>(r.id&&r.id===i.id)||(r.source===i.source&&r.line===i.line)||r.title===i.title));
      list($('tasks'),rows,i=>{const action=writable&&i.editable?async()=>{await api(i.id?pathFor(i)+"/complete":pathFor(i),{method:i.id?"POST":"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(i.id?{date}:{status:"[x]",type:i.type,title:i.title,details:i.details||{}})});await load()}:null;card($('tasks'),i.title,vals(i,'due')[0]||'',action,action?t.done:"")});
      list($('habits'),(habits.items||[]).filter(i=>!['[x]','[-]'].includes(i.status)),i=>{const finished=vals(i,'done').includes(date);const action=writable&&i.editable&&!finished?async()=>{const ds=vals(i,'done');if(!ds.includes(date))ds.push(date);await api(pathFor(i),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:i.status,type:i.type,title:i.title,details:{...i.details,done:ds}})});await load()}:null;card($('habits'),i.title,finished?"✓":i.status,action,action?t.done:"")});
      list($('notes'),notes.items||[],i=>card($('notes'),i.title,vals(i,'body')[0]||'',writable&&i.editable?()=>openEditor('N',i):null,'Edit'));
      const j=(journals.items||[]).find(i=>vals(i,'on').some(d=>String(d).slice(0,10)===date));$('journal').textContent=j?(vals(j,'body')[0]||j.title):t.empty;$('edit-journal').dataset.id=j?.id||'';$('edit-journal').disabled=!writable;
      $('feedback').textContent=date===today?t.today:date;
    }catch(e){$('feedback').textContent=t.error+' '+e.message}}
  function shift(n){const [y,m,d]=date.split('-').map(Number);date=new Date(Date.UTC(y,m-1,d+n)).toISOString().slice(0,10);load()}
  function openEditor(kind,item=null){if(!writable)return;edit={kind,item};$('editor-heading').textContent=kind==='J'?t.journal:t.notes;$('editor-title').value=item?.title||(kind==='J'?'Journal '+date:'');$('editor-body').value=vals(item,'body')[0]||'';$('editor-feedback').textContent='';$('editor').showModal();$('editor-title').focus()}
  async function boot(){translate();$('prev').onclick=()=>shift(-1);$('next').onclick=()=>shift(1);$('today').onclick=()=>{date=today;load()};$('date').onchange=()=>{if(/^\d{4}-\d\d-\d\d$/.test($('date').value)){date=$('date').value;load()}};
    $('open-capture').onclick=()=>writable&&$('capture-dialog').showModal();$('capture-form').onsubmit=async e=>{e.preventDefault();if(pending||!writable)return;pending=true;const b=$('capture-form').querySelector('[type=submit]');b.disabled=true;try{await api('/api/items/capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:$('capture-text').value})});$('capture-text').value='';$('capture-dialog').close();$('feedback').textContent=t.captured;await load()}catch(err){$('capture-feedback').textContent=t.captureError+err.message}finally{pending=false;b.disabled=false}};
    $('new-note').onclick=()=>openEditor('N');$('edit-journal').onclick=async()=>{const j=(await api('/api/items?type=J')).items||[];openEditor('J',j.find(i=>vals(i,'on').some(d=>String(d).slice(0,10)===date))||null)};
    $('editor-form').onsubmit=async e=>{e.preventDefault();if(!edit)return;const {kind,item}=edit,body=$('editor-body').value.trim();if(kind==='J'&&!body){$('editor-feedback').textContent=t.journalRequired;return}const details={...(item?.details||{})};if(body)details.body=[body];else delete details.body;if(kind==='J'&&!details.on)details.on=[date];const payload={status:'[N]',type:kind,title:$('editor-title').value.trim(),details};try{await api(item?pathFor(item):'/api/items',{method:item?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('editor').close();$('feedback').textContent=t.saved;await load()}catch(err){$('editor-feedback').textContent=t.saveError+err.message}};
    document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());const [config,health]=await Promise.all([api('/api/config'),api('/api/health')]);today=config.today;writable=!health.read_only&&Boolean(health.writable_path);['open-capture','new-note','edit-journal'].forEach(id=>$(id).disabled=!writable);if(!writable)$('feedback').textContent=t.readonly;date=/^\d{4}-\d\d-\d\d$/.test(params.get('date')||'')?params.get('date'):today;await load()}
  function bootError(e){$('feedback').textContent=t.error+e.message;['open-capture','new-note','edit-journal'].forEach(id=>$(id).disabled=true)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>boot().catch(bootError),{once:true});else boot().catch(bootError);
})();
