    let currentItems = [];
    let selectedItem = null;
    let bulkSelectedLines = new Set();
    let refreshTimer = null;
    let notificationTimer = null;
    let browserNotificationsEnabled = false;
    let seenNotifications = new Set();
    let appConfig = {};
    let graphLoaded = false;
    let _kioskDefaultTitle = null;
    let _kioskLastFingerprints = null;
    let _lastFocusedBeforeModal = null;
    const RECENT_ITEMS_STORAGE_KEY = "lifetxt_recent_items";
    const DASHBOARD_CARDS = ["today", "needs_attention", "completions", "projects"];
    const THEME_TOKEN_KEYS = new Set([
      "bg", "panel", "panel_2", "soft", "ink", "muted", "line", "line_strong",
      "accent", "accent_hover", "accent_soft", "accent_ink",
      "danger", "danger_soft", "warn", "warn_soft",
      "ok", "ok_soft", "info", "info_soft", "violet", "violet_soft",
      "shadow_1", "shadow_2", "shadow_3", "r_sm", "r_md", "r_lg",
    ]);

    async function api(path, options) {
      const response = await fetch(path, options);
      if (!response.ok) throw new Error(await response.text());
      return response.json();
    }
    function cssVarName(configKey) {
      return "--" + String(configKey || "").replace(/_/g, "-");
    }
    function applyConfiguredTheme() {
      const theme = appConfig?.web?.theme || {};
      for (const [key, value] of Object.entries(theme)) {
        if (!THEME_TOKEN_KEYS.has(key) || !String(value || "").trim()) continue;
        document.documentElement.style.setProperty(cssVarName(key), String(value).trim());
      }
    }
    // ── Interface language (web.language / ?lang=) ─────────────────
    // Translation is keyed by the English source string, so a new label in the
    // markup only needs a dictionary entry rather than an id or a data
    // attribute at the call site. Everything the user reads goes through one
    // pass: text nodes, title/placeholder/aria-label attributes, and strings
    // built in JavaScript via t().
    //
    // User content is never translated. Containers holding record data carry
    // data-no-i18n and the walker skips those subtrees entirely.
    const UI_STRINGS = {
      ja: {
        // Chrome and navigation
        "Plain text tasks, schedule, presence, and notes.": "プレーンテキストのタスク・予定・在席・メモ。",
        "Skip to content": "本文へスキップ",
        "Dashboard": "ダッシュボード",
        "Items": "アイテム",
        "Agenda": "予定",
        "Timeline": "タイムライン",
        "Calendar": "カレンダー",
        "Focus": "フォーカス",
        "Review": "レビュー",
        "Messages": "メッセージ",
        "Team": "チーム",
        "Status": "ステータス",
        "Notifications": "通知",
        "Stats": "統計",
        "Graph": "グラフ",
        "Display": "表示",
        "Kiosk": "キオスク",
        "Refresh": "更新",
        "Search": "検索",
        "Search (/)": "検索 (/)",
        "Apply": "適用",
        "All": "すべて",
        "All types": "すべての種類",
        "Add": "追加",
        "Create": "作成",
        "Cancel": "キャンセル",
        "Close": "閉じる",
        "Save": "保存",
        "Delete": "削除",
        "Edit": "編集",
        "Done": "完了",
        "Open": "未完了",
        "In Progress": "進行中",
        "Cancelled": "中止",
        "Deferred": "延期",
        "Pending": "保留",
        "Note": "メモ",
        "Details": "詳細",
        "Duplicate": "複製",
        "Export": "エクスポート",
        "Export…": "エクスポート…",
        "Import": "インポート",
        "Today": "今日",
        "Week": "週",
        "Month": "月",
        "Daily": "日次",
        "Weekly": "週次",
        "Monthly": "月次",
        "Asc": "昇順",
        "Desc": "降順",
        "Line": "行",
        "Title": "タイトル",
        "Type": "種類",
        "Project": "プロジェクト",
        "Tag": "タグ",
        "Priority": "優先度",
        "Owner": "担当",
        "Person": "人物",
        "Limit": "上限",
        "No grouping": "グループ化なし",
        "Saved view…": "保存済みビュー…",
        "Area…": "エリア…",
        "Set status…": "ステータスを設定…",
        "Set project…": "プロジェクトを設定…",
        "Clear": "クリア",
        "Clear filters": "フィルタを解除",
        "New record": "新規レコード",
        "Quick add": "クイック追加",
        "Commands…": "コマンド…",
        "Set status": "ステータス設定",
        "End status": "ステータス終了",
        "Commit": "コミット",
        "Commit message": "コミットメッセージ",
        "Copy ID": "IDをコピー",
        "Copy Link": "リンクをコピー",
        "Copy Title": "タイトルをコピー",
        "Copy Markdown": "Markdownをコピー",
        "Copy Line Number": "行番号をコピー",
        "Keyboard shortcuts": "キーボードショートカット",
        "Commands": "コマンド",
        "Search the same slash-command set as the TUI's /help command.": "TUIの /help と同じスラッシュコマンド一覧を検索できます。",
        "Search commands (name, alias, or summary)…": "コマンドを検索(名前・エイリアス・概要)…",
        "No command matches. Try a different search.": "一致するコマンドがありません。別のキーワードで検索してください。",
        "TUI only": "TUI専用",
        "Command palette (actions + jump to item)": "コマンドパレット(操作 + アイテムへ移動)",
        "Close modal / palette / blur input": "モーダル/パレットを閉じる・入力を解除",
        "Create a new record or select an editable row.": "レコードを新規作成するか、編集可能な行を選択してください。",
        "Search, filter, edit, and bulk-manage life.txt records.": "life.txt レコードの検索・絞り込み・編集・一括操作。",
        "Deadline": "期限",
        "Reminder": "リマインダー",
        "Habit": "習慣",
        "Event": "イベント",
        "Task": "タスク",
        "Journal": "ジャーナル",
        "Message": "メッセージ",
        "Presence": "在席",
        // KPI and count chrome
        "New": "新規",
        "Notifications ○": "通知 ○",
        "items": "件",
        "total": "合計",
        "open": "未完了",
        "done": "完了",
        "overdue": "期限超過",
        "Blocked": "ブロック中",
        "selected": "件選択中",
        "No items found.": "アイテムがありません。",
        "No agenda items found.": "予定はありません。",
        "Loading...": "読み込み中...",
        "Loading…": "読み込み中…",
        ", / . (Calendar)": ", / . (カレンダー)",
        "t / m (Calendar)": "t / m (カレンダー)",
        "Projects": "プロジェクト",
        "Journal & mood": "日誌と気分",
        "Needs attention": "要対応",
        "Nothing overdue or blocked.": "期限超過・ブロック中の項目はありません。",
        "Elapsed by project": "プロジェクト別の経過時間",
        "Completions (last 14 days)": "完了数 (直近14日)",
        "active": "進行中",
        "deferred": "保留",
        "available": "対応可能",
        "busy": "取り込み中",
        "maybe": "未定",
        "ongoing": "継続中",
        "note": "メモ",
        "action": "アクション",
        "weekly": "毎週",
        "dashboard": "ダッシュボード",
        "agenda": "予定",
        "timeline": "タイムライン",
        "calendar": "カレンダー",
        "focus": "フォーカス",
        "review": "レビュー",
        "messages": "メッセージ",
        "team": "チーム",
        "status": "ステータス",
        "notifications": "通知",
        "stats": "統計",
        "graph": "グラフ",
        "A compact overview of open work, agenda pressure, messages, and presence.": "未完了の作業・予定の逼迫度・メッセージ・在席状況をまとめて表示します。",
        "Combine presence, open workload, and recent messages per person.": "人ごとの在席状況・未完了の作業量・最近のメッセージをまとめます。",
        "Explore dependencies, references, parent-child links, and related records.": "依存関係・参照・親子リンク・関連レコードを可視化します。",
        "Filter message records and manage notification-oriented conversations.": "メッセージレコードを絞り込み、通知向けのやり取りを管理します。",
        "Inspect charted trends for tasks, projects, messages, and journal fields.": "タスク・プロジェクト・メッセージ・日誌の傾向をグラフで確認します。",
        "Place due, do, and event records on a month or week grid; click any entry to open it.": "期限・実施予定・イベントを月/週のグリッドに配置します。項目をクリックすると開きます。",
        "Prioritize open, actionable work and reduce noisy context while planning.": "着手可能な未完了作業を優先し、計画中の余計な情報を減らします。",
        "Review dated work in the selected range, including blocked and upcoming records.": "選択期間の日付付き作業を、ブロック中・今後の予定も含めて確認します。",
        "Review pending notification records, acknowledge them, or request browser alerts.": "未処理の通知レコードを確認し、既読にするかブラウザ通知を許可します。",
        "See dated records on a chronological board with empty-range guidance.": "日付付きレコードを時系列ボードで表示します。該当がない期間も案内します。",
        "Show the latest presence state for each person or active status records only.": "各人の最新の在席状態、または進行中のステータスのみを表示します。",
        "Summarize completed, carried, blocked, and planned work for a chosen period.": "指定期間の完了・繰り越し・ブロック中・予定の作業を要約します。",
        "Month/week calendar grid of dated records": "日付付きレコードの月/週カレンダー",
        "Views": "ビュー",
        "Actions": "操作",
        "Quick actions": "クイック操作",
        "Statistics": "統計",
        "Team board": "チームボード",
        "Status view": "ステータスビュー",
        "Tasks": "タスク",
        "Habits": "習慣",
        "Heatmap": "ヒートマップ",
        "Completed": "完了",
        "Mood": "気分",
        "Depth": "深さ",
        "Rows": "行数",
        "From": "開始",
        "To": "終了",
        "Force": "力学",
        "Ring": "リング",
        "Remove": "削除",
        "Back to top": "先頭へ戻る",
        "Go to Agenda": "予定へ移動",
        "Go to Calendar": "カレンダーへ移動",
        "Go to Dashboard": "ダッシュボードへ移動",
        "Go to Display mode": "ディスプレイモードへ移動",
        "Go to Focus": "フォーカスへ移動",
        "Go to Graph": "グラフへ移動",
        "Go to Items": "アイテムへ移動",
        "Go to Kiosk mode": "キオスクモードへ移動",
        "Go to Messages": "メッセージへ移動",
        "Go to Notifications": "通知へ移動",
        "Go to Review": "レビューへ移動",
        "Go to Stats": "統計へ移動",
        "Go to Stats view": "統計ビューへ移動",
        "Go to Status": "ステータスへ移動",
        "Go to Team": "チームへ移動",
        "Go to Timeline": "タイムラインへ移動",
        "Refresh all": "すべて更新",
        "Refresh calendar": "カレンダーを更新",
        "Refresh charts": "グラフを更新",
        "Refresh current view": "現在のビューを更新",
        "Refresh dashboard": "ダッシュボードを更新",
        "Refresh dependency graph": "依存グラフを更新",
        "Refresh focus list": "フォーカス一覧を更新",
        "Refresh graph": "グラフを更新",
        "Refresh review": "レビューを更新",
        "Refresh statistics": "統計を更新",
        "Refresh status": "ステータスを更新",
        "Refresh team board": "チームボードを更新",
        "Refresh timeline": "タイムラインを更新",
        "Filter by type": "種別で絞り込む",
        "Group items": "アイテムをグループ化",
        "Sort by": "並び替え",
        "Sort order": "並び順",
        "Active only": "進行中のみ",
        "Still open": "未完了",
        "Overdue": "期限超過",
        "Due today": "今日が期限",
        "Now": "現在",
        "Attention": "注意",
        "Inbox": "受信箱",
        "Unified Inbox": "統合インボックス",
        "Upcoming": "近日中",
        "Next actions": "次のアクション",
        "Waiting": "待機中",
        "Configuration errors": "設定エラー",
        "Nothing due today.": "本日期限の項目はありません。",
        "Nothing actionable.": "実行可能な項目はありません。",
        "Nothing overdue.": "期限超過の項目はありません。",
        "Nothing blocked.": "ブロック中の項目はありません。",
        "Nothing waiting.": "待機中の項目はありません。",
        "Nothing upcoming.": "近日中の予定はありません。",
        "All projects green.": "すべてのプロジェクトは良好です。",
        "Inbox is empty.": "受信箱は空です。",
        "No unread messages.": "未読メッセージはありません。",
        "No open habits.": "未完了の習慣はありません。",
        "The Daily Command Center: what to do now, what needs attention, the Unified Inbox, and what is coming up.":
          "Daily Command Center: 今すべきこと、注意が必要な項目、統合インボックス、近日中の予定をまとめて表示します。",
        "Daily Command Center: now, attention, inbox, upcoming": "Daily Command Center: 現在・注意・受信箱・近日中",
        "Refresh Today": "Todayを更新",
        "Open tasks": "未完了タスク",
        "Habits tracked": "記録中の習慣",
        "Journal entries": "日誌エントリ",
        "Items blocked by open dependencies": "未完了の依存によりブロック中のアイテム",
        "Elapsed": "経過時間",
        "Current time": "現在時刻",
        "This week": "今週",
        "This month": "今月",
        "Last week": "先週",
        "Last month": "先月",
        "Next 24h": "今後24時間",
        "Review range": "レビュー期間",
        "Review start date": "レビュー開始日",
        "Review end date": "レビュー終了日",
        "Timeline range": "タイムライン期間",
        "Max rows": "最大行数",
        "Apply a saved view": "保存済みビューを適用",
        "Filter by area": "エリアで絞り込む",
        "Max agenda rows (0 = all)": "予定の最大行数 (0 = すべて)",
        "Root id (optional)": "ルートID (任意)",
        "Month grid": "月グリッド",
        "Single-week grid": "週グリッド",
        "By Status": "ステータス別",
        "By Type": "種別別",
        "‹ Prev": "‹ 前へ",
        "Next ›": "次へ ›",
        "Previous period (,)": "前の期間 (,)",
        "Next period (.)": "次の期間 (.)",
        "Jump to current period (t)": "現在の期間へ (t)",
        "Previous / next calendar period": "前/次のカレンダー期間",
        "Jump to today / toggle month/week": "今日へ移動 / 月・週の切り替え",
        "Calendar navigation": "カレンダー操作",
        "Layered left-to-right": "左から右へのレイヤー配置",
        "Layered top-to-bottom": "上から下へのレイヤー配置",
        "Force-directed layout (physics simulation)": "力学レイアウト (物理シミュレーション)",
        "Ring layout (focus in center)": "リングレイアウト (中心にフォーカス)",
        "New item": "新規アイテム",
        "New Record": "新規レコード",
        "New message": "新規メッセージ",
        "Import raw": "生の行を取り込む",
        "New item (opens the record editor)": "新規アイテム (レコードエディタを開く)",
        "Create a new record (n)": "新規レコードを作成 (n)",
        "Add a task due today… (Enter)": "今日が期限のタスクを追加… (Enter)",
        "Buy milk @home #errand !high ^tomorrow   (or a full [ ] T line)": "牛乳を買う @home #errand !high ^tomorrow   (完全な [ ] T 行も可)",
        "Paste a raw life.txt line to populate the form": "life.txt の行を貼り付けるとフォームに反映されます",
        "Suggested keys: due: est: project: tag: assignee: depends_on: parent:": "推奨キー: due: est: project: tag: assignee: depends_on: parent:",
        "Hover or focus the ? badges for field help. Type-specific suggested detail keys appear above the Details box.": "? バッジにカーソルを合わせると項目の説明が表示されます。種別ごとの推奨キーは詳細欄の上に表示されます。",
        "Update life.txt": "life.txt を更新",
        "Clear selection": "選択を解除",
        "Delete selected": "選択項目を削除",
        "Mark selected as done": "選択項目を完了にする",
        "Set project on selected items": "選択項目のプロジェクトを設定",
        "Set status of selected items": "選択項目のステータスを設定",
        "Toggle bulk selection on focused item": "フォーカス中の項目の一括選択を切り替え",
        "Item context menu": "アイテムのコンテキストメニュー",
        "Copy deep link to this item": "このアイテムへのリンクをコピー",
        "Copy item ID to clipboard": "アイテムIDをクリップボードにコピー",
        "Copy item as Markdown": "アイテムをMarkdownとしてコピー",
        "Open actions": "操作を開く",
        "Open agenda": "予定を開く",
        "Open focus": "フォーカスを開く",
        "Open focused item in detail modal": "フォーカス中の項目を詳細モーダルで開く",
        "Jump to line number": "行番号へ移動",
        "Jump to line number (opens detail modal)": "行番号へ移動 (詳細モーダルを開く)",
        "Prev / next item in detail modal": "詳細モーダルで前/次の項目へ",
        "Prev / next status filter": "前/次のステータスフィルタ",
        "Move keyboard focus down / up in item list": "アイテム一覧でフォーカスを上下に移動",
        "Export items as CSV": "アイテムをCSVで書き出す",
        "Export items as JSON": "アイテムをJSONで書き出す",
        "Export items as Markdown": "アイテムをMarkdownで書き出す",
        "Download the currently filtered items": "絞り込み中のアイテムをダウンロード",
        "Download chart data as CSV": "グラフのデータをCSVでダウンロード",
        "Download graph as PNG": "グラフをPNGでダウンロード",
        "Download graph as SVG": "グラフをSVGでダウンロード",
        "Toggle dark mode": "ダークモードを切り替え",
        "Toggle dark mode (d)": "ダークモードを切り替え (d)",
        "Toggle high-contrast theme": "ハイコントラストテーマを切り替え",
        "Toggle reduced motion": "アニメーション低減を切り替え",
        "Toggle compact density": "コンパクト表示を切り替え",
        "Toggle fullscreen": "全画面を切り替え",
        "Toggle fullscreen (f)": "全画面を切り替え (f)",
        "Toggle display mode": "ディスプレイモードを切り替え",
        "Toggle kiosk mode": "キオスクモードを切り替え",
        "Toggle quick-add bar": "クイック追加バーを切り替え",
        "Toggle agenda blocked filter": "予定のブロック中フィルタを切り替え",
        "Toggle between active-only and latest record for everyone": "「進行中のみ」と「全員の最新レコード」を切り替え",
        "Cycle: show all / only blocked / hide blocked": "切り替え: すべて表示 / ブロック中のみ / ブロック中を隠す",
        "Exit display mode": "ディスプレイモードを終了",
        "Exit kiosk mode (Esc)": "キオスクモードを終了 (Esc)",
        "Open a read-focused wall display mode": "閲覧向けのウォールディスプレイモードを開く",
        "Open or toggle Display mode": "ディスプレイモードを開く/切り替える",
        "Command palette": "コマンドパレット",
        "Command palette (Ctrl+K)": "コマンドパレット (Ctrl+K)",
        "Ctrl+K display": "Ctrl+K 表示",
        "Type / for commands, or search items…": "/ でコマンド、そのまま入力でアイテム検索…",
        "Focus search": "検索にフォーカス",
        "Show / hide this help": "このヘルプを表示/非表示",
        "Keyboard shortcuts help": "キーボードショートカットのヘルプ",
        "Close modal / palette / blur input / exit kiosk": "モーダル/パレットを閉じる・入力を解除・キオスクを終了",
        "Show undo history": "取り消し履歴を表示",
        "Enable alerts": "通知を有効化",
        "Notifications: not yet requested": "通知: 未許可",
        "Open notifications / enable browser alerts": "通知を開く / ブラウザ通知を有効化",
        "No elapsed time recorded.": "経過時間の記録はありません。",

        // Contextual help (data-help / CONTROL_HELP / VIEW_HELP), shown on
        // hover or keyboard focus via showUiHelp().
        "Toggle light and dark theme. Add ?theme=light or ?theme=dark to force a wall-display theme.":
          "ライト/ダークテーマを切り替えます。?theme=light または ?theme=dark を付けると壁掛け表示用のテーマを固定できます。",
        "High-contrast mode increases borders and text contrast for low-visibility displays.":
          "ハイコントラストモードは、見えにくい画面向けに枠線と文字のコントラストを強めます。",
        "Reduced motion disables most transitions and animation-heavy feedback.":
          "アニメーション低減は、ほとんどの遷移効果や動きの多い演出を無効にします。",
        "Compact density hides long body previews and fits more records on small screens.":
          "コンパクト表示は本文の長いプレビューを隠し、小さい画面により多くのレコードを表示します。",
        "Use browser fullscreen for kiosk or display boards. Press f to toggle.":
          "キオスクやディスプレイボード向けにブラウザの全画面表示を使います。f キーで切り替え。",
        "Open notification records and optionally request browser notification permission.":
          "通知レコードを開きます。必要に応じてブラウザ通知の許可もリクエストします。",
        "Reload the active view from disk/API without changing filters. Press r as a shortcut.":
          "フィルタを変更せずに現在のビューをディスク/APIから再読み込みします。ショートカットは r。",
