(() => {
  "use strict";
  const copy={en:{skip:"Skip to Planner",web:"Full Web UI",eyebrow:"Your day, in one place",title:"Day Planner",weekTitle:"Week Planner",today:"Today",choose:"Choose date",day:"Day",week:"Week",previousDay:"Previous day",nextDay:"Next day",previousWeek:"Previous week",nextWeek:"Next week",weekOf:"Week of",selected:"Selected",todayMarker:"TODAY",past:"Past",todayState:"Today",future:"Future",schedule:"Schedule",tasks:"Tasks",habits:"Habits",notes:"Notes",journal:"Journal",reviewActivity:"Review / Activity",moreReview:"Show more",newNote:"＋ Add a note",writeJournal:"Write today's journal",capture:"＋ Quick Capture",prompt:"What do you want to remember?",submitCapture:"Capture",labelTitle:"Title",labelBody:"Details / journal",save:"Save",close:"Close",empty:"Nothing here for this day.",emptyDate:"No dated items.",showDay:"Open day view",event:"Event",reminder:"Reminder",deadline:"Deadline",task:"Task",done:"Mark done",saved:"Saved.",captured:"Captured.",readonly:"This workspace is read-only. Changes are disabled.",loading:"Loading…",error:"Could not load the Planner: ",captureError:"Capture failed: ",saveError:"Could not save: ",journalRequired:"Enter journal text before saving."},ja:{skip:"Plannerへ移動",web:"Web UI全体",eyebrow:"今日をひとつの画面に",title:"デイリープランナー",weekTitle:"週間プランナー",today:"今日",choose:"日付を選ぶ",day:"日",week:"週",previousDay:"前の日",nextDay:"次の日",previousWeek:"前の週",nextWeek:"次の週",weekOf:"週の期間",selected:"選択中",todayMarker:"今日",past:"過去",todayState:"今日",future:"未来",schedule:"予定",tasks:"タスク",habits:"習慣",notes:"メモ",journal:"日誌",reviewActivity:"レビュー / アクティビティ",moreReview:"さらに表示",newNote:"＋ メモを追加",writeJournal:"今日の日誌を書く",capture:"＋ クイックキャプチャ",prompt:"覚えておきたいことは何ですか？",submitCapture:"記録",labelTitle:"タイトル",labelBody:"詳細 / 日誌",save:"保存",close:"閉じる",empty:"この日の記録はありません。",emptyDate:"予定はありません。",showDay:"日表示を開く",event:"予定",reminder:"リマインダー",deadline:"期限",task:"タスク",done:"完了を記録",saved:"保存しました。",captured:"記録しました。",readonly:"このworkspaceは読み取り専用です。変更できません。",loading:"読み込み中…",error:"Plannerを読み込めませんでした：",captureError:"記録できませんでした：",saveError:"保存できませんでした：",journalRequired:"日誌の内容を入力してください。"}};
  const NOTE_PAGE_SIZE=5;
  let notesPage=null, noteRows=[], notesBusy=false, loadGeneration=0;
  const $=id=>document.getElementById(id), params=new URLSearchParams(location.search);let scopeArea=params.get('area')||'',scopeView=params.get('saved_view')||'';
  let requestedLang=params.get("lang"),lang=["en","ja"].includes(requestedLang)?requestedLang:((navigator.language||"en").slice(0,2)==="ja"?"ja":"en"), t=copy.en, today="", date="", view=["week","month"].includes(params.get("view"))?params.get("view"):"day", writable=false, edit=null, pending=false;
  function translate(){t=copy[lang];Object.assign(t,lang==="ja"?{emptyNotes:"通常のメモはありません。",moreNotes:"さらに表示",editNote:"編集",viewSelector:"Plannerの表示",anchorDate:"表示の基準日",month:"月",monthTitle:"月間プランナー",previousMonth:"前の月",nextMonth:"次の月",densityNone:"予定なし",densityLow:"少ない",densityMedium:"普通",densityHigh:"多い",items:"件",outsideMonth:"表示月の外",scope:"スコープ",all:"すべて",customize:"カスタマイズ",sections:"Dayセクション",density:"密度",comfortable:"標準",compact:"コンパクト",apply:"適用",reset:"workspaceの既定値に戻す",moveUp:"上へ",moveDown:"下へ",showSection:"表示"}:{emptyNotes:"No ordinary Notes.",moreNotes:"Load more",editNote:"Edit",viewSelector:"Planner view",anchorDate:"View anchor date",month:"Month",monthTitle:"Month Planner",previousMonth:"Previous month",nextMonth:"Next month",densityNone:"No dated items",densityLow:"Low density",densityMedium:"Medium density",densityHigh:"High density",items:"items",outsideMonth:"Outside selected month",scope:"Scope",all:"All",customize:"Customize",sections:"Day sections",density:"Density",comfortable:"Comfortable",compact:"Compact",apply:"Apply",reset:"Reset to workspace defaults",moveUp:"Move up",moveDown:"Move down",showSection:"Show"});document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(n=>n.textContent=t[n.dataset.i18n]||n.textContent);$('view-switch').setAttribute("aria-label",t.viewSelector);document.title=(view==="week"?t.weekTitle:view==="month"?t.monthTitle:t.title)+" · life.txt"}
  async function api(path,options={}){const r=await fetch(path,options);const raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw Error(d.message||d.detail||"Request failed");return d}
  const vals=(item,key)=>Array.isArray(item?.details?.[key])?item.details[key]:item?.details?.[key]?[item.details[key]]:[];
  const pathFor=i=>i.id?"/api/items/id/"+encodeURIComponent(i.id):i.line&&i.editable?"/api/items/"+encodeURIComponent(i.line):null;
  function card(target,title,meta,action,label){const n=document.createElement("article");n.className="card";const main=document.createElement("div"),strong=document.createElement("strong");strong.textContent=title||"";main.append(strong);if(meta){const p=document.createElement("p");p.textContent=meta;main.append(p)}n.append(main);if(action){const b=document.createElement("button");b.type="button";b.textContent=label;b.addEventListener("click",action);n.append(b)}target.append(n)}
  function list(target,items,render){target.replaceChildren();if(!items.length){const p=document.createElement("p");p.className="empty";p.textContent=t.empty;target.append(p);return}items.forEach(x=>render(x))}
  function updateUrl(){const u=new URL(location.href);if(view!=="day"||date!==today)u.searchParams.set("date",date);else u.searchParams.delete("date");if(view!=="day")u.searchParams.set("view",view);else u.searchParams.delete("view");if(scopeArea)u.searchParams.set("area",scopeArea);else u.searchParams.delete("area");if(scopeView)u.searchParams.set("saved_view",scopeView);else u.searchParams.delete("saved_view");lang==="en"?u.searchParams.delete("lang"):u.searchParams.set("lang",lang);history.replaceState({},"",u.pathname+u.search)}
  function scopeQuery(){const p=new URLSearchParams();if(scopeArea)p.set('area',scopeArea);if(scopeView)p.set('saved_view',scopeView);return p.toString()?("&"+p.toString()):''}
  function setView(next){view=next;translate();$('day-view').hidden=view!=="day";$('week-view').hidden=view!=="week";$('month-view').hidden=view!=="month";$('view-day').setAttribute("aria-pressed",String(view==="day"));$('view-week').setAttribute("aria-pressed",String(view==="week"));$('view-month').setAttribute("aria-pressed",String(view==="month"));$('title').textContent=view==="week"?t.weekTitle:view==="month"?t.monthTitle:t.title;updateUrl();load()}
  const dayDate=(value,delta)=>{const [y,m,d]=value.split('-').map(Number);return new Date(Date.UTC(y,m-1,d+delta)).toISOString().slice(0,10)}; function dayPosition(){return date<today?"past":date>today?"future":"today"} function temporalLabel(){return {past:t.past,today:t.todayState,future:t.future}[dayPosition()]} function updateTemporalContext(){const node=$("temporal-context");if(!node)return;const position=dayPosition();node.dataset.position=position;$("day-view").dataset.position=position;node.textContent=temporalLabel()+" · "+date;node.setAttribute("aria-label",temporalLabel()+", "+date)}
  function weekStart(value){const weekday=new Date(value+"T00:00:00Z").getUTCDay();return dayDate(value,-((weekday+6)%7))}
  function matchTime(record,match){const start=String(match.start||""),time=start.includes("T")?start.slice(11,16):"";if(!time)return "";if(time!=="00:00")return time;const values=Object.values(record.details||{}).flat().map(String);return values.some(value=>value===time||value.includes("T"+time))?time:""}
  function weekLabel(start,end){const locale=lang==="ja"?"ja-JP":"en-US", a=new Date(start+"T00:00:00Z"),b=new Date(end+"T00:00:00Z");return new Intl.DateTimeFormat(locale,{month:"short",day:"numeric",timeZone:"UTC"}).format(a)+" – "+new Intl.DateTimeFormat(locale,{month:"short",day:"numeric",year:a.getUTCFullYear()!==b.getUTCFullYear()?"numeric":undefined,timeZone:"UTC"}).format(b)}
  function renderWeek(records,start){const target=$('week-days');target.replaceChildren();const buckets=Array.from({length:7},()=>[]);for(const record of records){if(!["E","R","D","T"].includes(record.type))continue;const matches=Array.isArray(record.matches)?record.matches:[];for(const match of matches){const occurrence=String(match.start||"").slice(0,10),index=Math.round((Date.parse(occurrence+"T00:00:00Z")-Date.parse(start+"T00:00:00Z"))/86400000);if(index>=0&&index<7)buckets[index].push({record,match})}}for(const bucket of buckets)bucket.sort((a,b)=>String(a.match.start||"").localeCompare(String(b.match.start||""))||String(a.record.title||"").localeCompare(String(b.record.title||""),lang));
    for(let index=0;index<7;index++){const dateValue=dayDate(start,index),day=new Date(dateValue+"T00:00:00Z"),section=document.createElement('section'),head=document.createElement('h3'),button=document.createElement('button'),items=buckets[index];section.className='week-day';if(dateValue===date)section.classList.add('is-selected');if(dateValue===today)section.classList.add('is-today');button.type='button';button.className='week-day-link';button.setAttribute('aria-label',new Intl.DateTimeFormat(lang==='ja'?'ja-JP':'en-US',{dateStyle:'full',timeZone:'UTC'}).format(day)+', '+t.showDay);button.setAttribute('aria-current',dateValue===date?'date':'false');const weekday=new Intl.DateTimeFormat(lang==='ja'?'ja-JP':'en-US',{weekday:'short',day:'numeric',month:'short',timeZone:'UTC'}).format(day);button.textContent=weekday;if(dateValue===today){const marker=document.createElement('span');marker.className='state-marker';marker.textContent=t.todayMarker;button.append(' ',marker)}if(dateValue===date){const marker=document.createElement('span');marker.className='state-marker selected-marker';marker.textContent=t.selected;button.append(' ',marker)}button.addEventListener('click',()=>{date=dateValue;setView('day')});head.append(button);section.append(head);if(!items.length){const empty=document.createElement('p');empty.className='week-empty';empty.textContent=t.emptyDate;section.append(empty)}else{for(const {record,match} of items){const row=document.createElement('article'),meta=document.createElement('p'),title=document.createElement('strong'),kind=document.createElement('span'),when=matchTime(record,match);row.className='week-record';meta.className='week-record-meta';kind.className='type-marker';kind.textContent=t[{E:'event',R:'reminder',D:'deadline',T:'task'}[record.type]];meta.append(kind);if(when){const time=document.createElement('time');time.textContent=when;time.dateTime=match.start;meta.append(' ',time)}title.textContent=record.title||'';row.append(meta,title);section.append(row)}}target.append(section)}$('week-range').textContent=weekLabel(start,dayDate(start,6));}
  async function loadWeek(){const start=weekStart(date),end=dayDate(start,6);$('week-range').textContent=weekLabel(start,end);$('week-days').replaceChildren();$('feedback').textContent=t.loading;try{const agenda=await api('/api/agenda?from='+start+'&to='+end);renderWeek(agenda.records||[],start);$('feedback').textContent=(date===today?t.today+" · ":"")+t.weekOf+" "+weekLabel(start,end)}catch(e){$('feedback').textContent=t.error+' '+e.message}}
  function monthStart(value){return value.slice(0,7)+"-01"}
  function monthShift(value,delta){const [y,m]=value.split('-').map(Number);return new Date(Date.UTC(y,m-1+delta,1)).toISOString().slice(0,10)}
  function monthLabel(value){return new Intl.DateTimeFormat(lang==="ja"?"ja-JP":"en-US",{year:"numeric",month:"long",timeZone:"UTC"}).format(new Date(value+"T00:00:00Z"))}
  function densityText(count){if(!count)return t.densityNone;return (count<=2?t.densityLow:count<=5?t.densityMedium:t.densityHigh)+" · "+count+" "+t.items}
  function renderMonth(records,start,end){const counts=new Map();for(const record of records){if(!["E","R","D","T"].includes(record.type))continue;for(const match of Array.isArray(record.matches)?record.matches:[]){const occurrence=String(match.start||"").slice(0,10);if(occurrence>=start&&occurrence<=end)counts.set(occurrence,(counts.get(occurrence)||0)+1)}}const grid=$('month-grid'),weekdays=$('month-weekdays');grid.replaceChildren();weekdays.replaceChildren();const locale=lang==="ja"?"ja-JP":"en-US";for(let i=0;i<7;i++){const label=document.createElement('span');label.textContent=new Intl.DateTimeFormat(locale,{weekday:'narrow',timeZone:'UTC'}).format(new Date(dayDate('2026-09-07',i)+'T00:00:00Z'));weekdays.append(label)}for(let value=start;value<=end;value=dayDate(value,1)){const count=counts.get(value)||0,outside=value.slice(0,7)!==date.slice(0,7),button=document.createElement('button'),number=document.createElement('span'),density=document.createElement('span'),full=new Intl.DateTimeFormat(locale,{dateStyle:'full',timeZone:'UTC'}).format(new Date(value+'T00:00:00Z'));button.type='button';button.className='month-day';if(outside)button.classList.add('is-outside');if(value===date)button.classList.add('is-selected');if(value===today)button.classList.add('is-today');button.setAttribute('aria-label',[full,densityText(count),outside?t.outsideMonth:'',value===today?t.todayMarker:'',value===date?t.selected:''].filter(Boolean).join(', '));button.setAttribute('aria-current',value===date?'date':'false');number.className='month-number';number.textContent=String(Number(value.slice(8)));density.className='month-density density-'+(count===0?'none':count<=2?'low':count<=5?'medium':'high');density.textContent=count?String(Math.min(count,9)):'·';density.setAttribute('aria-hidden','true');button.append(number,density);button.addEventListener('click',()=>{date=value;setView('day')});grid.append(button)}$('month-heading').textContent=monthLabel(monthStart(date))}
  async function loadMonth(){const first=monthStart(date),start=weekStart(first),next=monthShift(first,1),nextWeek=weekStart(next),end=dayDate(nextWeek,nextWeek===next?-1:6);$('month-heading').textContent=monthLabel(first);$('month-grid').replaceChildren();$('feedback').textContent=t.loading;try{const agenda=await api('/api/agenda?from='+start+'&to='+end);renderMonth(agenda.records||[],start,end);$('feedback').textContent=monthLabel(first)}catch(e){$('feedback').textContent=t.error+' '+e.message}}
  function renderNotes(){
    list($('notes'),noteRows,i=>card($('notes'),i.title,vals(i,'body')[0]||'',writable&&i.editable?()=>openEditor('N',i):null,t.editNote));
    if(!noteRows.length)$('notes').firstElementChild.textContent=t.emptyNotes;
    $('notes-count').textContent=noteRows.length+' / '+(notesPage?.total||0)+' '+t.items;
    $('more-notes').hidden=!notesPage?.has_more;
    $('more-notes').disabled=notesBusy;
  }
  function renderReview(review){const panel=$('review-panel');panel.hidden=dayPosition()!=="past";if(panel.hidden)return;$('review-summary').textContent=(review.counts?.events||0)+" events · "+(review.complete?"complete":"incomplete");const rows=[...(review.completed||[]),...(review.changed||[]),...(review.reopened_or_rescheduled||[])];const expanded=panel.dataset.expanded==="true";list($('review-activity'),rows.slice(0,expanded?rows.length:5),row=>card($('review-activity'),row.title||row.event||"",row.event||"",null));$('more-review').hidden=expanded||rows.length<=5;$('more-review').onclick=()=>{panel.dataset.expanded="true";renderReview(review)}}
  async function moreNotes(){
    if(notesBusy||!notesPage?.has_more)return;
    const generation=loadGeneration,selectedDate=date,previous=notesPage;
    notesBusy=true;renderNotes();
    try{
      const page=await api('/api/notes?date='+selectedDate+'&limit='+NOTE_PAGE_SIZE+'&offset='+previous.next_offset);
      if(generation!==loadGeneration||view!=='day'||selectedDate!==date)return;
      if(page.revision!==previous.revision){await load();return}
      noteRows.push(...(page.items||[]));notesPage=page;
    }catch(e){if(generation===loadGeneration)$('feedback').textContent=t.error+e.message}
    finally{if(generation===loadGeneration){notesBusy=false;renderNotes()}}
  }
  async function load(){const generation=++loadGeneration;notesBusy=false;notesPage=null;noteRows=[];renderNotes();if(!date)return;$('date').value=date;updateTemporalContext();$('date').setAttribute("aria-label",view!=="day"?t.anchorDate:t.choose);updateUrl();$('day-view').hidden=view!=="day";$('week-view').hidden=view!=="week";$('month-view').hidden=view!=="month";$('dock').hidden=view!=="day";$('view-day').setAttribute("aria-pressed",String(view==="day"));$('view-week').setAttribute("aria-pressed",String(view==="week"));$('view-month').setAttribute("aria-pressed",String(view==="month"));$('title').textContent=view==="week"?t.weekTitle:view==="month"?t.monthTitle:t.title;$('prev').setAttribute("aria-label",view==="week"?t.previousWeek:view==="month"?t.previousMonth:t.previousDay);$('next').setAttribute("aria-label",view==="week"?t.nextWeek:view==="month"?t.nextMonth:t.nextDay);if(view==="week"){await loadWeek();return}if(view==="month"){await loadMonth();return}$('feedback').textContent=t.loading;
    try{const [day,agenda,habits,notes,journals,tasks,review]=await Promise.all([api('/api/command-center?date='+date+scopeQuery()),api('/api/agenda?from='+date+'&to='+date+scopeQuery()),api('/api/items?type=H&open_only=true'),api('/api/notes?date='+date+'&limit='+NOTE_PAGE_SIZE+scopeQuery()),api('/api/items?type=J'),api('/api/items?type=T&open_only=true'),dayPosition()==="past"?api('/api/temporal-review?date='+date+'&limit=100'+scopeQuery()):Promise.resolve(null)]);
      if(generation!==loadGeneration)return;
      list($('schedule'),(agenda.records||[]).filter(x=>["E","R","D"].includes(x.type)),x=>card($('schedule'),x.title,[x.when,x.status].filter(Boolean).join(' · ')));
      const refs=[...(day.due_today||[]),...(date===today?(day.next_actions||[]):[])].filter(x=>x.kind==="T"&&!x.blocked);const rows=(tasks.items||[]).filter(i=>refs.some(r=>(r.id&&r.id===i.id)||(r.source===i.source&&r.line===i.line)||r.title===i.title));
      list($('tasks'),rows,i=>{const action=dayPosition()==="today"&&writable&&i.editable?async()=>{await api(i.id?pathFor(i)+"/complete":pathFor(i),{method:i.id?"POST":"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(i.id?{date}:{status:"[x]",type:i.type,title:i.title,details:i.details||{}})});await load()}:null;card($('tasks'),i.title,vals(i,'due')[0]||'',action,action?t.done:"")});
      list($('habits'),(habits.items||[]).filter(i=>!['[x]','[-]'].includes(i.status)),i=>{const finished=vals(i,'done').includes(date);const action=dayPosition()==="today"&&writable&&i.editable&&!finished?async()=>{const ds=vals(i,'done');if(!ds.includes(date))ds.push(date);await api(pathFor(i),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:i.status,type:i.type,title:i.title,details:{...i.details,done:ds}})});await load()}:null;card($('habits'),i.title,finished?"✓":i.status,action,action?t.done:"")});
      notesPage=notes;noteRows=notes.items||[];renderNotes();
      $('review-panel').dataset.expanded="false";renderReview(review||{});
      const j=(journals.items||[]).find(i=>vals(i,'on').some(d=>String(d).slice(0,10)===date));$('journal').textContent=j?(vals(j,'body')[0]||j.title):t.empty;$('edit-journal').dataset.id=j?.id||'';$('edit-journal').disabled=!writable;
      $('feedback').textContent=date===today?t.today:date;
    }catch(e){if(generation===loadGeneration)$('feedback').textContent=t.error+' '+e.message}}
  function shift(n){date=view==="month"?monthShift(monthStart(date),n):dayDate(date,n*(view==="week"?7:1));load()}
  const sectionIds=["schedule","tasks","habits","notes","journal","review"];
  let plannerDefaults={sections:sectionIds,hidden_sections:[],density:"comfortable"},plannerPreference=null;
  function normalizePlannerPreference(value){const source=value||plannerDefaults,sections=Array.isArray(source.sections)?source.sections:sectionIds,ordered=[...new Set(sections.filter(id=>sectionIds.includes(id))),...sectionIds.filter(id=>!sections.includes(id))];return {sections:ordered,hidden_sections:[...new Set((Array.isArray(source.hidden_sections)?source.hidden_sections:[]).filter(id=>sectionIds.includes(id)))],density:["comfortable","compact"].includes(source.density)?source.density:"comfortable"}}
  function preference(){if(plannerPreference)return plannerPreference;try{const raw=localStorage.getItem("lifetxt_planner_prefs_v1");plannerPreference=raw?normalizePlannerPreference(JSON.parse(raw)):normalizePlannerPreference(plannerDefaults)}catch(_){plannerPreference=normalizePlannerPreference(plannerDefaults)}return plannerPreference}
  function applyPlannerPreference(){const pref=preference(),day=$('day-view');day.classList.toggle('density-compact',pref.density==='compact');for(const id of sectionIds){const node=$(id)?.closest('section');if(node)node.hidden=pref.hidden_sections.includes(id)}for(const id of pref.sections){const node=$(id)?.closest('section');if(node)day.append(node)} }
  function renderPreferenceControls(){const pref=preference(),target=$('section-preferences');target.replaceChildren();for(const id of pref.sections){const row=document.createElement('div');row.className='preference-row';row.dataset.section=id;const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=!pref.hidden_sections.includes(id);check.dataset.section=id;label.append(check,' ',id);const up=document.createElement('button'),down=document.createElement('button');up.type=down.type='button';up.textContent=t.moveUp;down.textContent=t.moveDown;up.setAttribute('aria-label',t.moveUp+' '+id);down.setAttribute('aria-label',t.moveDown+' '+id);up.onclick=()=>{const before=row.previousElementSibling;if(before)target.insertBefore(row,before)};down.onclick=()=>{const after=row.nextElementSibling;if(after)target.insertBefore(after,row)};row.append(label,up,down);target.append(row)}$('density').value=pref.density}
  function savePlannerPreference(value){plannerPreference=normalizePlannerPreference(value);try{localStorage.setItem("lifetxt_planner_prefs_v1",JSON.stringify(plannerPreference))}catch(_){ }applyPlannerPreference()}
  function openEditor(kind,item=null){if(!writable)return;edit={kind,item};$('editor-heading').textContent=kind==='J'?t.journal:t.notes;$('editor-title').value=item?.title||(kind==='J'?'Journal '+date:'');$('editor-body').value=vals(item,'body')[0]||'';$('editor-feedback').textContent='';$('editor').showModal();$('editor-title').focus()}
  async function boot(){translate();$('more-notes').onclick=moreNotes;$('customize').onclick=()=>{renderPreferenceControls();$('customize-dialog').showModal()};$('customize-form').onsubmit=e=>{e.preventDefault();const rows=[...$('section-preferences').children],hidden=rows.filter(row=>!row.querySelector('input').checked).map(row=>row.dataset.section);savePlannerPreference({sections:rows.map(row=>row.dataset.section),hidden_sections:hidden,density:$('density').value});$('customize-dialog').close()};$('reset-customization').onclick=()=>{plannerPreference=normalizePlannerPreference(plannerDefaults);try{localStorage.removeItem("lifetxt_planner_prefs_v1")}catch(_){ }applyPlannerPreference();renderPreferenceControls()};$('prev').onclick=()=>shift(-1);$('next').onclick=()=>shift(1);$('today').onclick=()=>{date=today;load()};$('prev').setAttribute('aria-label',t.previousDay);$('next').setAttribute('aria-label',t.nextDay);$('view-day').onclick=()=>setView('day');$('view-week').onclick=()=>setView('week');$('view-month').onclick=()=>setView('month');$('date').onchange=()=>{if(/^\d{4}-\d\d-\d\d$/.test($('date').value)){date=$('date').value;load()}};
    $('open-capture').onclick=()=>writable&&$('capture-dialog').showModal();$('capture-form').onsubmit=async e=>{e.preventDefault();if(pending||!writable)return;pending=true;const b=$('capture-form').querySelector('[type=submit]');b.disabled=true;try{await api('/api/items/capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:$('capture-text').value})});$('capture-text').value='';$('capture-dialog').close();$('feedback').textContent=t.captured;await load()}catch(err){$('capture-feedback').textContent=t.captureError+err.message}finally{pending=false;b.disabled=false}};
    $('new-note').onclick=()=>openEditor('N');$('edit-journal').onclick=async()=>{const j=(await api('/api/items?type=J')).items||[];openEditor('J',j.find(i=>vals(i,'on').some(d=>String(d).slice(0,10)===date))||null)};
    $('editor-form').onsubmit=async e=>{e.preventDefault();if(!edit)return;const {kind,item}=edit,body=$('editor-body').value.trim();if(kind==='J'&&!body){$('editor-feedback').textContent=t.journalRequired;return}const details={...(item?.details||{})};if(body)details.body=[body];else delete details.body;if(kind==='J'&&!details.on)details.on=[date];const payload={status:'[N]',type:kind,title:$('editor-title').value.trim(),details};try{await api(item?pathFor(item):'/api/items',{method:item?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('editor').close();$('feedback').textContent=t.saved;await load()}catch(err){$('editor-feedback').textContent=t.saveError+err.message}};
    document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());const [config,health,areas,views]=await Promise.all([api('/api/config'),api('/api/health'),api('/api/areas'),api('/api/saved-views')]);today=config.today;plannerDefaults=normalizePlannerPreference(config.web?.planner);const scopeSelect=$("scope");(areas.areas||[]).forEach(a=>{const o=document.createElement("option");o.value="area:"+a.name;o.textContent="Area: "+a.name;scopeSelect.append(o)});(views.views||[]).forEach(v=>{const o=document.createElement("option");o.value="saved_view:"+v.name;o.textContent="Saved View: "+v.name;scopeSelect.append(o)});scopeSelect.value=scopeArea?("area:"+scopeArea):scopeView?("saved_view:"+scopeView):"";scopeSelect.onchange=()=>{const value=scopeSelect.value;scopeArea=value.startsWith("area:")?value.slice(5):"";scopeView=value.startsWith("saved_view:")?value.slice(11):"";updateUrl();load()};writable=!health.read_only&&Boolean(health.writable_path);['open-capture','new-note','edit-journal'].forEach(id=>$(id).disabled=!writable);if(!writable)$('feedback').textContent=t.readonly;date=/^\d{4}-\d\d-\d\d$/.test(params.get('date')||'')?params.get('date'):today;applyPlannerPreference();await load()}
  function bootError(e){$('feedback').textContent=t.error+e.message;['open-capture','new-note','edit-journal'].forEach(id=>$(id).disabled=true)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>boot().catch(bootError),{once:true});else boot().catch(bootError);
})();
