(() => {
  "use strict";
  const copy={en:{skip:"Skip to Planner",web:"Full Web UI",eyebrow:"Your day, in one place",title:"Day Planner",weekTitle:"Week Planner",today:"Today",choose:"Choose date",day:"Day",week:"Week",previousDay:"Previous day",nextDay:"Next day",previousWeek:"Previous week",nextWeek:"Next week",weekOf:"Week of",selected:"Selected",todayMarker:"TODAY",schedule:"Schedule",tasks:"Tasks",habits:"Habits",notes:"Notes",journal:"Journal",newNote:"＋ Add a note",writeJournal:"Write today's journal",capture:"＋ Quick Capture",prompt:"What do you want to remember?",submitCapture:"Capture",labelTitle:"Title",labelBody:"Details / journal",save:"Save",close:"Close",empty:"Nothing here for this day.",emptyDate:"No dated items.",showDay:"Open day view",event:"Event",reminder:"Reminder",deadline:"Deadline",task:"Task",done:"Mark done",saved:"Saved.",captured:"Captured.",readonly:"This workspace is read-only. Changes are disabled.",loading:"Loading…",error:"Could not load the Planner: ",captureError:"Capture failed: ",saveError:"Could not save: ",journalRequired:"Enter journal text before saving."},ja:{skip:"Plannerへ移動",web:"Web UI全体",eyebrow:"今日をひとつの画面に",title:"デイリープランナー",weekTitle:"週間プランナー",today:"今日",choose:"日付を選ぶ",day:"日",week:"週",previousDay:"前の日",nextDay:"次の日",previousWeek:"前の週",nextWeek:"次の週",weekOf:"週の期間",selected:"選択中",todayMarker:"今日",schedule:"予定",tasks:"タスク",habits:"習慣",notes:"メモ",journal:"日誌",newNote:"＋ メモを追加",writeJournal:"今日の日誌を書く",capture:"＋ クイックキャプチャ",prompt:"覚えておきたいことは何ですか？",submitCapture:"記録",labelTitle:"タイトル",labelBody:"詳細 / 日誌",save:"保存",close:"閉じる",empty:"この日の記録はありません。",emptyDate:"予定はありません。",showDay:"日表示を開く",event:"予定",reminder:"リマインダー",deadline:"期限",task:"タスク",done:"完了を記録",saved:"保存しました。",captured:"記録しました。",readonly:"このworkspaceは読み取り専用です。変更できません。",loading:"読み込み中…",error:"Plannerを読み込めませんでした：",captureError:"記録できませんでした：",saveError:"保存できませんでした：",journalRequired:"日誌の内容を入力してください。"}};
  const $=id=>document.getElementById(id), params=new URLSearchParams(location.search);
  let lang=params.get("lang")==="ja"?"ja":((navigator.language||"en").slice(0,2)==="ja"?"ja":"en"), t=copy.en, today="", date="", view=params.get("view")==="week"?"week":"day", writable=false, edit=null, pending=false;
  function translate(){t=copy[lang];t.viewSelector=lang==="ja"?"Plannerの表示":"Planner view";t.anchorDate=lang==="ja"?"週の基準日":"Anchor date";document.documentElement.lang=lang;document.querySelectorAll("[data-i18n]").forEach(n=>n.textContent=t[n.dataset.i18n]||n.textContent);$('view-switch').setAttribute("aria-label",t.viewSelector);document.title=(view==="week"?t.weekTitle:t.title)+" · life.txt"}
  async function api(path,options={}){const r=await fetch(path,options);const raw=await r.text();let d={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw Error(d.message||d.detail||"Request failed");return d}
  const vals=(item,key)=>Array.isArray(item?.details?.[key])?item.details[key]:item?.details?.[key]?[item.details[key]]:[];
  const pathFor=i=>i.id?"/api/items/id/"+encodeURIComponent(i.id):i.line&&i.editable?"/api/items/"+encodeURIComponent(i.line):null;
  function card(target,title,meta,action,label){const n=document.createElement("article");n.className="card";const main=document.createElement("div"),strong=document.createElement("strong");strong.textContent=title||"";main.append(strong);if(meta){const p=document.createElement("p");p.textContent=meta;main.append(p)}n.append(main);if(action){const b=document.createElement("button");b.type="button";b.textContent=label;b.addEventListener("click",action);n.append(b)}target.append(n)}
  function list(target,items,render){target.replaceChildren();if(!items.length){const p=document.createElement("p");p.className="empty";p.textContent=t.empty;target.append(p);return}items.forEach(x=>render(x))}
  function updateUrl(){const u=new URL(location.href);if(view==="week"||date!==today)u.searchParams.set("date",date);else u.searchParams.delete("date");if(view==="week")u.searchParams.set("view","week");else u.searchParams.delete("view");lang==="en"?u.searchParams.delete("lang"):u.searchParams.set("lang",lang);history.replaceState({},"",u.pathname+u.search)}
  function setView(next){view=next;translate();$('day-view').hidden=view==="week";$('week-view').hidden=view!=="week";$('view-day').setAttribute("aria-pressed",String(view==="day"));$('view-week').setAttribute("aria-pressed",String(view==="week"));$('title').textContent=view==="week"?t.weekTitle:t.title;updateUrl();load()}
  const dayDate=(value,delta)=>{const [y,m,d]=value.split('-').map(Number);return new Date(Date.UTC(y,m-1,d+delta)).toISOString().slice(0,10)};
  function weekStart(value){const weekday=new Date(value+"T00:00:00Z").getUTCDay();return dayDate(value,-((weekday+6)%7))}
  function matchTime(record,match){const start=String(match.start||""),time=start.includes("T")?start.slice(11,16):"";if(!time)return "";if(time!=="00:00")return time;const values=Object.values(record.details||{}).flat().map(String);return values.some(value=>value===time||value.includes("T"+time))?time:""}
  function weekLabel(start,end){const locale=lang==="ja"?"ja-JP":"en-US", a=new Date(start+"T00:00:00Z"),b=new Date(end+"T00:00:00Z");return new Intl.DateTimeFormat(locale,{month:"short",day:"numeric",timeZone:"UTC"}).format(a)+" – "+new Intl.DateTimeFormat(locale,{month:"short",day:"numeric",year:a.getUTCFullYear()!==b.getUTCFullYear()?"numeric":undefined,timeZone:"UTC"}).format(b)}
  function renderWeek(records,start){const target=$('week-days');target.replaceChildren();const buckets=Array.from({length:7},()=>[]);for(const record of records){if(!["E","R","D","T"].includes(record.type))continue;const matches=Array.isArray(record.matches)?record.matches:[];for(const match of matches){const occurrence=String(match.start||"").slice(0,10),index=Math.round((Date.parse(occurrence+"T00:00:00Z")-Date.parse(start+"T00:00:00Z"))/86400000);if(index>=0&&index<7)buckets[index].push({record,match})}}for(const bucket of buckets)bucket.sort((a,b)=>String(a.match.start||"").localeCompare(String(b.match.start||""))||String(a.record.title||"").localeCompare(String(b.record.title||""),lang));
    for(let index=0;index<7;index++){const dateValue=dayDate(start,index),day=new Date(dateValue+"T00:00:00Z"),section=document.createElement('section'),head=document.createElement('h3'),button=document.createElement('button'),items=buckets[index];section.className='week-day';if(dateValue===date)section.classList.add('is-selected');if(dateValue===today)section.classList.add('is-today');button.type='button';button.className='week-day-link';button.setAttribute('aria-label',new Intl.DateTimeFormat(lang==='ja'?'ja-JP':'en-US',{dateStyle:'full',timeZone:'UTC'}).format(day)+', '+t.showDay);button.setAttribute('aria-current',dateValue===date?'date':'false');const weekday=new Intl.DateTimeFormat(lang==='ja'?'ja-JP':'en-US',{weekday:'short',day:'numeric',month:'short',timeZone:'UTC'}).format(day);button.textContent=weekday;if(dateValue===today){const marker=document.createElement('span');marker.className='state-marker';marker.textContent=t.todayMarker;button.append(' ',marker)}if(dateValue===date){const marker=document.createElement('span');marker.className='state-marker selected-marker';marker.textContent=t.selected;button.append(' ',marker)}button.addEventListener('click',()=>{date=dateValue;setView('day')});head.append(button);section.append(head);if(!items.length){const empty=document.createElement('p');empty.className='week-empty';empty.textContent=t.emptyDate;section.append(empty)}else{for(const {record,match} of items){const row=document.createElement('article'),meta=document.createElement('p'),title=document.createElement('strong'),kind=document.createElement('span'),when=matchTime(record,match);row.className='week-record';meta.className='week-record-meta';kind.className='type-marker';kind.textContent=t[{E:'event',R:'reminder',D:'deadline',T:'task'}[record.type]];meta.append(kind);if(when){const time=document.createElement('time');time.textContent=when;time.dateTime=match.start;meta.append(' ',time)}title.textContent=record.title||'';row.append(meta,title);section.append(row)}}target.append(section)}$('week-range').textContent=weekLabel(start,dayDate(start,6));}
  async function loadWeek(){const start=weekStart(date),end=dayDate(start,6);$('week-range').textContent=weekLabel(start,end);$('week-days').replaceChildren();$('feedback').textContent=t.loading;try{const agenda=await api('/api/agenda?from='+start+'&to='+end);renderWeek(agenda.records||[],start);$('feedback').textContent=(date===today?t.today+" · ":"")+t.weekOf+" "+weekLabel(start,end)}catch(e){$('feedback').textContent=t.error+' '+e.message}}
  async function load(){if(!date)return;$('date').value=date;$('date').setAttribute("aria-label",view==="week"?t.anchorDate:t.choose);updateUrl();$('day-view').hidden=view==="week";$('week-view').hidden=view!=="week";$('dock').hidden=view==="week";$('view-day').setAttribute("aria-pressed",String(view==="day"));$('view-week').setAttribute("aria-pressed",String(view==="week"));$('title').textContent=view==="week"?t.weekTitle:t.title;$('prev').setAttribute("aria-label",view==="week"?t.previousWeek:t.previousDay);$('next').setAttribute("aria-label",view==="week"?t.nextWeek:t.nextDay);if(view==="week"){await loadWeek();return}$('feedback').textContent=t.loading;
    try{const [day,agenda,habits,notes,journals,tasks]=await Promise.all([api('/api/command-center?date='+date),api('/api/agenda?from='+date+'&to='+date),api('/api/items?type=H&open_only=true'),api('/api/items?type=N&limit=20'),api('/api/items?type=J'),api('/api/items?type=T&open_only=true')]);
      list($('schedule'),(agenda.records||[]).filter(x=>["E","R","D"].includes(x.type)),x=>card($('schedule'),x.title,[x.when,x.status].filter(Boolean).join(' · ')));
      const refs=[...(day.due_today||[]),...(date===today?(day.next_actions||[]):[])].filter(x=>x.kind==="T"&&!x.blocked);const rows=(tasks.items||[]).filter(i=>refs.some(r=>(r.id&&r.id===i.id)||(r.source===i.source&&r.line===i.line)||r.title===i.title));
      list($('tasks'),rows,i=>{const action=writable&&i.editable?async()=>{await api(i.id?pathFor(i)+"/complete":pathFor(i),{method:i.id?"POST":"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(i.id?{date}:{status:"[x]",type:i.type,title:i.title,details:i.details||{}})});await load()}:null;card($('tasks'),i.title,vals(i,'due')[0]||'',action,action?t.done:"")});
      list($('habits'),(habits.items||[]).filter(i=>!['[x]','[-]'].includes(i.status)),i=>{const finished=vals(i,'done').includes(date);const action=writable&&i.editable&&!finished?async()=>{const ds=vals(i,'done');if(!ds.includes(date))ds.push(date);await api(pathFor(i),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:i.status,type:i.type,title:i.title,details:{...i.details,done:ds}})});await load()}:null;card($('habits'),i.title,finished?"✓":i.status,action,action?t.done:"")});
      list($('notes'),notes.items||[],i=>card($('notes'),i.title,vals(i,'body')[0]||'',writable&&i.editable?()=>openEditor('N',i):null,'Edit'));
      const j=(journals.items||[]).find(i=>vals(i,'on').some(d=>String(d).slice(0,10)===date));$('journal').textContent=j?(vals(j,'body')[0]||j.title):t.empty;$('edit-journal').dataset.id=j?.id||'';$('edit-journal').disabled=!writable;
      $('feedback').textContent=date===today?t.today:date;
    }catch(e){$('feedback').textContent=t.error+' '+e.message}}
  function shift(n){date=dayDate(date,n*(view==="week"?7:1));load()}
  function openEditor(kind,item=null){if(!writable)return;edit={kind,item};$('editor-heading').textContent=kind==='J'?t.journal:t.notes;$('editor-title').value=item?.title||(kind==='J'?'Journal '+date:'');$('editor-body').value=vals(item,'body')[0]||'';$('editor-feedback').textContent='';$('editor').showModal();$('editor-title').focus()}
  async function boot(){translate();$('prev').onclick=()=>shift(-1);$('next').onclick=()=>shift(1);$('today').onclick=()=>{date=today;load()};$('prev').setAttribute('aria-label',t.previousDay);$('next').setAttribute('aria-label',t.nextDay);$('view-day').onclick=()=>setView('day');$('view-week').onclick=()=>setView('week');$('date').onchange=()=>{if(/^\d{4}-\d\d-\d\d$/.test($('date').value)){date=$('date').value;load()}};
    $('open-capture').onclick=()=>writable&&$('capture-dialog').showModal();$('capture-form').onsubmit=async e=>{e.preventDefault();if(pending||!writable)return;pending=true;const b=$('capture-form').querySelector('[type=submit]');b.disabled=true;try{await api('/api/items/capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:$('capture-text').value})});$('capture-text').value='';$('capture-dialog').close();$('feedback').textContent=t.captured;await load()}catch(err){$('capture-feedback').textContent=t.captureError+err.message}finally{pending=false;b.disabled=false}};
    $('new-note').onclick=()=>openEditor('N');$('edit-journal').onclick=async()=>{const j=(await api('/api/items?type=J')).items||[];openEditor('J',j.find(i=>vals(i,'on').some(d=>String(d).slice(0,10)===date))||null)};
    $('editor-form').onsubmit=async e=>{e.preventDefault();if(!edit)return;const {kind,item}=edit,body=$('editor-body').value.trim();if(kind==='J'&&!body){$('editor-feedback').textContent=t.journalRequired;return}const details={...(item?.details||{})};if(body)details.body=[body];else delete details.body;if(kind==='J'&&!details.on)details.on=[date];const payload={status:'[N]',type:kind,title:$('editor-title').value.trim(),details};try{await api(item?pathFor(item):'/api/items',{method:item?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('editor').close();$('feedback').textContent=t.saved;await load()}catch(err){$('editor-feedback').textContent=t.saveError+err.message}};
    document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());const [config,health]=await Promise.all([api('/api/config'),api('/api/health')]);today=config.today;writable=!health.read_only&&Boolean(health.writable_path);['open-capture','new-note','edit-journal'].forEach(id=>$(id).disabled=!writable);if(!writable)$('feedback').textContent=t.readonly;date=/^\d{4}-\d\d-\d\d$/.test(params.get('date')||'')?params.get('date'):today;await load()}
  function bootError(e){$('feedback').textContent=t.error+e.message;['open-capture','new-note','edit-journal'].forEach(id=>$(id).disabled=true)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>boot().catch(bootError),{once:true});else boot().catch(bootError);
})();
