        "Single-week grid": "週グリッド",
        "By Status": "ステータス別",
        "By Type": "種別別",
        "‹ Prev": "‹ 前へ",
        "Next ›": "次へ ›",
        "Previous period (,)": "前の期間 (,)",
        "Next period (.)": "次の期間 (.)",
        "Jump to current period (t)": "現在の期間へ (t)",
        "Previous / next calendar period": "前/次のカレンダー期間",
        "Jump to today / toggle month/week": "今日へ移動 / 月・週の切り替え",
        "Calendar navigation": "カレンダー操作",
        "Layered left-to-right": "左から右へのレイヤー配置",
        "Layered top-to-bottom": "上から下へのレイヤー配置",
        "Force-directed layout (physics simulation)": "力学レイアウト (物理シミュレーション)",
        "Ring layout (focus in center)": "リングレイアウト (中心にフォーカス)",
        "New item": "新規アイテム",
        "New Record": "新規レコード",
        "New message": "新規メッセージ",
        "Import raw": "生の行を取り込む",
        "New item (opens the record editor)": "新規アイテム (レコードエディタを開く)",
        "Create a new record (n)": "新規レコードを作成 (n)",
        "Add a task due today… (Enter)": "今日が期限のタスクを追加… (Enter)",
        "Buy milk @home #errand !high ^tomorrow   (or a full [ ] T line)": "牛乳を買う @home #errand !high ^tomorrow   (完全な [ ] T 行も可)",
        "Paste a raw life.txt line to populate the form": "life.txt の行を貼り付けるとフォームに反映されます",
        "Suggested keys: due: est: project: tag: assignee: depends_on: parent:": "推奨キー: due: est: project: tag: assignee: depends_on: parent:",
        "Hover or focus the ? badges for field help. Type-specific suggested detail keys appear above the Details box.": "? バッジにカーソルを合わせると項目の説明が表示されます。種別ごとの推奨キーは詳細欄の上に表示されます。",
        "Update life.txt": "life.txt を更新",
        "Clear selection": "選択を解除",
        "Delete selected": "選択項目を削除",
        "Mark selected as done": "選択項目を完了にする",
        "Set project on selected items": "選択項目のプロジェクトを設定",
        "Set status of selected items": "選択項目のステータスを設定",
        "Toggle bulk selection on focused item": "フォーカス中の項目の一括選択を切り替え",
        "Item context menu": "アイテムのコンテキストメニュー",
        "Copy deep link to this item": "このアイテムへのリンクをコピー",
        "Copy item ID to clipboard": "アイテムIDをクリップボードにコピー",
        "Copy item as Markdown": "アイテムをMarkdownとしてコピー",
        "Open actions": "操作を開く",
        "Open agenda": "予定を開く",
        "Open focus": "フォーカスを開く",
        "Open focused item in detail modal": "フォーカス中の項目を詳細モーダルで開く",
        "Jump to line number": "行番号へ移動",
        "Jump to line number (opens detail modal)": "行番号へ移動 (詳細モーダルを開く)",
        "Prev / next item in detail modal": "詳細モーダルで前/次の項目へ",
        "Prev / next status filter": "前/次のステータスフィルタ",
        "Move keyboard focus down / up in item list": "アイテム一覧でフォーカスを上下に移動",
        "Export items as CSV": "アイテムをCSVで書き出す",
        "Export items as JSON": "アイテムをJSONで書き出す",
        "Export items as Markdown": "アイテムをMarkdownで書き出す",
        "Download the currently filtered items": "絞り込み中のアイテムをダウンロード",
        "Download chart data as CSV": "グラフのデータをCSVでダウンロード",
        "Download graph as PNG": "グラフをPNGでダウンロード",
        "Download graph as SVG": "グラフをSVGでダウンロード",
        "Toggle dark mode": "ダークモードを切り替え",
        "Toggle dark mode (d)": "ダークモードを切り替え (d)",
        "Toggle high-contrast theme": "ハイコントラストテーマを切り替え",
        "Toggle reduced motion": "アニメーション低減を切り替え",
        "Toggle compact density": "コンパクト表示を切り替え",
        "Toggle fullscreen": "全画面を切り替え",
        "Toggle fullscreen (f)": "全画面を切り替え (f)",
        "Toggle display mode": "ディスプレイモードを切り替え",
        "Toggle kiosk mode": "キオスクモードを切り替え",
        "Toggle quick-add bar": "クイック追加バーを切り替え",
        "Toggle agenda blocked filter": "予定のブロック中フィルタを切り替え",
        "Toggle between active-only and latest record for everyone": "「進行中のみ」と「全員の最新レコード」を切り替え",
        "Cycle: show all / only blocked / hide blocked": "切り替え: すべて表示 / ブロック中のみ / ブロック中を隠す",
        "Exit display mode": "ディスプレイモードを終了",
        "Exit kiosk mode (Esc)": "キオスクモードを終了 (Esc)",
        "Open a read-focused wall display mode": "閲覧向けのウォールディスプレイモードを開く",
        "Open or toggle Display mode": "ディスプレイモードを開く/切り替える",
        "Command palette": "コマンドパレット",
        "Command palette (Ctrl+K)": "コマンドパレット (Ctrl+K)",
        "Ctrl+K display": "Ctrl+K 表示",
        "Type / for commands, or search items…": "/ でコマンド、そのまま入力でアイテム検索…",
        "Focus search": "検索にフォーカス",
        "Show / hide this help": "このヘルプを表示/非表示",
        "Keyboard shortcuts help": "キーボードショートカットのヘルプ",
        "Close modal / palette / blur input / exit kiosk": "モーダル/パレットを閉じる・入力を解除・キオスクを終了",
        "Show undo history": "取り消し履歴を表示",
        "Enable alerts": "通知を有効化",
        "Notifications: not yet requested": "通知: 未許可",
        "Open notifications / enable browser alerts": "通知を開く / ブラウザ通知を有効化",
        "No elapsed time recorded.": "経過時間の記録はありません。",

        // Contextual help (data-help / CONTROL_HELP / VIEW_HELP), shown on
        // hover or keyboard focus via showUiHelp().
        "Toggle light and dark theme. Add ?theme=light or ?theme=dark to force a wall-display theme.":
          "ライト/ダークテーマを切り替えます。?theme=light または ?theme=dark を付けると壁掛け表示用のテーマを固定できます。",
        "High-contrast mode increases borders and text contrast for low-visibility displays.":
          "ハイコントラストモードは、見えにくい画面向けに枠線と文字のコントラストを強めます。",
        "Reduced motion disables most transitions and animation-heavy feedback.":
          "アニメーション低減は、ほとんどの遷移効果や動きの多い演出を無効にします。",
        "Compact density hides long body previews and fits more records on small screens.":
          "コンパクト表示は本文の長いプレビューを隠し、小さい画面により多くのレコードを表示します。",
        "Use browser fullscreen for kiosk or display boards. Press f to toggle.":
          "キオスクやディスプレイボード向けにブラウザの全画面表示を使います。f キーで切り替え。",
        "Open notification records and optionally request browser notification permission.":
          "通知レコードを開きます。必要に応じてブラウザ通知の許可もリクエストします。",
        "Reload the active view from disk/API without changing filters. Press r as a shortcut.":
          "フィルタを変更せずに現在のビューをディスク/APIから再読み込みします。ショートカットは r。",