#!/usr/bin/env python
"""Generate Formula/lifetxt.rb for one lifetxt release.

Reads the SHA256SUMS file .github/workflows/standalone-binaries.yml (#570)
attaches to every release and produces a Homebrew Formula that installs the
matching standalone binary directly -- no build-from-source step, matching
the "thin adapter around the canonical release artifact" design used by
every other package-manager integration in this project (see
docs/en/distribution.md). The generated file is what
.github/workflows/homebrew-tap.yml pushes to the Eruhitsuji/homebrew-tap
repository; see that workflow and packaging/homebrew/README.md for the
one-time maintainer setup (a HOMEBREW_TAP_TOKEN secret) this depends on.

Usage:
    python scripts/generate_homebrew_formula.py \\
        --version 1.0.0 \\
        --sha256sums path/to/SHA256SUMS \\
        --output packaging/homebrew/generated/lifetxt.rb
"""

from __future__ import print_function

import argparse
import sys
from pathlib import Path

REPO = "Eruhitsuji/lifetxt"
DESCRIPTION = "Parser, validator, converter, CLI, and optional web UI for life.txt"

# artifact filename (from #570) -> (Homebrew OS block, Homebrew CPU condition)
_TARGETS = [
    ("lifetxt-macos-arm64", "macos", "arm"),
    ("lifetxt-macos-x86_64", "macos", "intel"),
    ("lifetxt-linux-arm64", "linux", "arm"),
    ("lifetxt-linux-x86_64", "linux", "intel"),
]


def parse_sha256sums(text):
    """Return {filename: sha256} from a `sha256sum`-style SHA256SUMS file."""
    checksums = {}
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        parts = line.split(None, 1)
        if len(parts) != 2:
            continue
        digest, name = parts
        checksums[name.lstrip("*")] = digest.lower()
    return checksums


def build_formula(version, checksums, repo):
    missing = [name for name, _, _ in _TARGETS if name not in checksums]
    if missing:
        raise ValueError(
            "SHA256SUMS is missing entries for: %s" % ", ".join(sorted(missing))
        )

    def url_for(name):
        return "https://github.com/%s/releases/download/v%s/%s" % (repo, version, name)

    macos_arm = next(n for n, os_, cpu in _TARGETS if os_ == "macos" and cpu == "arm")
    macos_intel = next(
        n for n, os_, cpu in _TARGETS if os_ == "macos" and cpu == "intel"
    )
    linux_arm = next(n for n, os_, cpu in _TARGETS if os_ == "linux" and cpu == "arm")
    linux_intel = next(
        n for n, os_, cpu in _TARGETS if os_ == "linux" and cpu == "intel"
    )

    return """# This file is generated by scripts/generate_homebrew_formula.py in the
# Eruhitsuji/lifetxt repository. Do not hand-edit -- edit the generator
# instead, or it will be silently overwritten on the next release.
class Lifetxt < Formula
  desc "{description}"
  homepage "https://github.com/{repo}"
  version "{version}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "{macos_arm_url}"
      sha256 "{macos_arm_sha}"
    else
      url "{macos_intel_url}"
      sha256 "{macos_intel_sha}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "{linux_arm_url}"
      sha256 "{linux_arm_sha}"
    else
      url "{linux_intel_url}"
      sha256 "{linux_intel_sha}"
    end
  end

  def install
    downloaded = Dir["lifetxt-*"].first
    bin.install downloaded => "lifetxt"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/lifetxt --version")
    (testpath/"life.txt").write("[ ] T Sample due:2026-01-01\\n")
    system bin/"lifetxt", "check", "life.txt"
  end
end
""".format(
        description=DESCRIPTION,
        repo=repo,
        version=version,
        macos_arm_url=url_for(macos_arm),
        macos_arm_sha=checksums[macos_arm],
        macos_intel_url=url_for(macos_intel),
        macos_intel_sha=checksums[macos_intel],
        linux_arm_url=url_for(linux_arm),
        linux_arm_sha=checksums[linux_arm],
        linux_intel_url=url_for(linux_intel),
        linux_intel_sha=checksums[linux_intel],
    )


def build_parser():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True, help="Release version, e.g. 1.0.0")
    parser.add_argument(
        "--sha256sums",
        required=True,
        help="Path to the release's SHA256SUMS file (from #570's artifacts)",
    )
    parser.add_argument("--repo", default=REPO, help="owner/repo for download URLs")
    parser.add_argument(
        "--output",
        default="packaging/homebrew/generated/lifetxt.rb",
        help="Path to write the Formula to",
    )
    return parser


def main(argv=None):
    args = build_parser().parse_args(argv)
    sums_text = Path(args.sha256sums).read_text(encoding="utf-8")
    checksums = parse_sha256sums(sums_text)
    try:
        formula = build_formula(args.version, checksums, args.repo)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(formula, encoding="utf-8", newline="\n")
    print(str(output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
