"""Apply the ticket/project report roadmap update once, then delete this file."""

from pathlib import Path

path = Path("todo.md")
lines = path.read_text(encoding="utf-8").splitlines()

intro = "This is the active roadmap after the 2026-07-25 delegated-mutation, remote directory/package attachment, subprocess fault-matrix, verified-backup restoration, operator-authorization, remote-write clock-contract, development-ticket-core, and shared ticket/project-report batches. The safety batch adds a restart-safe delegated-process proposal format that edits only a private temporary copy, validates life.txt output, persists exact source/proposal/content/diff revisions, supports inspect/apply/reject after process restart, rejects proposal tampering, and preserves one-winner/one-conflict semantics; exposes directory-reference, deterministic package, reconcile, open-plan, bounded chunk-read, package-manifest inspection, and transaction-status contracts through Web and MCP with exact item/attachment/metadata revisions, confined server-side package sources, stable retry IDs, duplicate-ID recovery reports, no remote opener execution, and capability discovery; makes an offset-aware client timestamp optionally mandatory for every writable Web and MCP operation while leaving parser-only endpoints usable; expands the subprocess `os._exit` drill from two boundaries to a deterministic 16-boundary matrix with automatic pre-journal orphan cleanup, normal stale-lock recovery, resume/compensation, and repeated terminal recovery; adds integrity-verified restore from an immutable backup through a separate working copy plus optional operator allow-list enforcement; publishes seven safety schemas and raises the Draft 2020-12 bundle from 45 to 52 documents; and documents the full workflow in English and Japanese. The ticket batches add the `record:ticket` model and local management operations plus a versioned, read-only `ticket-project-report-v1` aggregation contract with deterministic summary, board, attention, dependency, due-date, stale, assignment, severity, and estimate/elapsed metrics. Completed sub-items are removed from the roadmap rather than repeated. Remaining P0 work is limited to real observe-to-required deployment evidence, adapter-specific adoption of the delegated proposal contract, real remote-client/restart/divergence evidence, physical power/storage/platform failure evidence, encrypted and role-controlled evidence operations, shared timezone fixtures, and real terminal/browser/SMTP verification. Remaining ticket work focuses on workflow/history, exact-revision writes, richer planning records, configuration-backed custom fields, and cross-surface adoption of the shared report rather than rebuilding ticket aggregation. The CLI-only deterministic two-counter runtime remains planned work and is not claimed as implemented. The previous detailed roadmap remains preserved in [`docs/roadmap-archive-2026-07-20.md`](docs/roadmap-archive-2026-07-20.md)."

project_paragraph = "The read side now exists in [`lifetxt/projects.py`](lifetxt/projects.py): projects are built from `project:` details and `record:project|milestone|risk|issue|decision|meeting` records (documented custom keys, no new item type); a schema-backed registry (`projects` config + `project-registry-v1.schema.json`) supplies display name, aliases, default source/assignee/area, templates, and visibility while changing data stays in records; `project list|show|health|timeline|workload|risks` plus a single `project show` hub aggregation and a `portfolio` comparison are wired in the CLI; every derived number exposes its formula and missing-data limitations (progress = done/non-cancelled tasks, transparent green/yellow/red health, blocked via `depends_on:`, overdue via reference date); `project new` and `project add milestone|risk|decision|meeting` append records to the resolved workspace write target with `--dry-run`; a `project-summary-v1.schema.json` is published; and English/Japanese `docs/*/projects.md` plus `examples/config/projects.lifetxt.json` document it. The shared [`lifetxt/ticket_projects.py`](lifetxt/ticket_projects.py) report layer now adds project-scoped development-ticket summaries, deterministic status boards, overlapping attention queues, dependency-known/unknown separation, date-aware overdue counts, stale/unassigned/high-severity counts, estimate/elapsed coverage, paired variance, formulas, and caveats under `ticket-project-report-v1`; it is directly inspectable through `python -m lifetxt.ticket_projects summary|board|attention`. Remaining work adds writes-that-move, integration of this shared report into the existing Project Hub and Portfolio commands and other public surfaces, privacy, and an explicit boundary between generic project issues and development tickets."

ticket_paragraph = "The core now exists in [`lifetxt/tickets.py`](lifetxt/tickets.py): a canonical field registry (`ticket-field-registry-v1`) and `ticket-v1.schema.json`; the `record:ticket` marker; the detailed `ticket_status` → coarse life.txt status map with config override and TK003 contradiction diagnostics; a versioned `ticketing` config section (trackers, priorities, severities, components, id_prefix, required_fields, defaults) with registry (TK004) and required-field (TK005) validation; `ticket new|list|show|edit|assign|close|reopen|link|unlink|validate` wired in the CLI with auto id generation, workspace-aware write targets, `--dry-run`, and JSON output; `ticket show` aggregating fields, relations, and incoming links via the shared link graph; and read-only MCP `list_tickets`/`get_ticket`/`validate_tickets`. The shared [`lifetxt/ticket_projects.py`](lifetxt/ticket_projects.py) layer now publishes deterministic project/global ticket summaries, boards, and attention queues through `python -m lifetxt.ticket_projects summary|board|attention`; reports distinguish confirmed open dependencies from absent/unevaluated dependencies, keep date-only deadlines current through the UTC date, accept explicit reference times and stale windows, expose effective terminal/high-severity sets, report estimate/elapsed coverage and paired variance, embed formulas/caveats, and conform to `ticket-project-report-v1.schema.json`. English/Japanese documentation exists in `docs/*/tickets.md` and `docs/*/ticket-projects.md`."

replacements = {
    "Last updated: ": "Last updated: 2026-07-25 (updated x115)",
    "This is the active roadmap after ": intro,
    "8. Add Development Ticket Management Core:": "8. Harden the implemented Development Ticket Management Core: typed custom fields, exact-revision writes, relation rules, bulk operations, registry-backed query/sort/completion, fixtures, and cross-surface adoption of the shared ticket/project report.",
    "The read side now exists in [`lifetxt/projects.py`]": project_paragraph,
    "- [ ] Expose the existing `project`/`portfolio` operations": "- [ ] Expose the existing `project`/`portfolio` operations through TUI, Web, MCP, saved views, and remote read-only clients where capabilities permit, reusing `lifetxt/projects.py` and the implemented `lifetxt/ticket_projects.py` report contract rather than reimplementing either aggregation per surface. Thread the same reference time, stale window, terminal-status set, high-severity set, project scope, formulas, caveats, and dependency-unknown counts through every adapter; add capability and schema-version discovery before remote clients depend on the report.",
    "The core now exists in [`lifetxt/tickets.py`]": ticket_paragraph,
}

seen = set()
output = []
for line in lines:
    replaced = False
    for prefix, value in replacements.items():
        if line.startswith(prefix):
            output.append(value)
            seen.add(prefix)
            replaced = True
            break
    if line.startswith("- [ ] Extend Project Hub, Portfolio, command center"):
        output.extend([
            "- [ ] Integrate `ticket-project-report-v1` into the main `ticket` and `project` command trees, Project Hub, Portfolio, command center, health, workload, review, notification, TUI, Web, MCP, saved-view, and remote read-only surfaces. Reuse report objects and schema payloads directly instead of recalculating open/by-status, blocked, dependency-unknown, overdue, unassigned, high-severity, stale, estimate/elapsed, or count-progress values. Preserve the standalone `python -m lifetxt.ticket_projects` commands for diagnostics and backward-compatible scripting.",
            "- [ ] Resolve default terminal statuses, status display order, priority order, and high-severity values from the effective versioned `ticketing` registry while retaining explicit library/CLI overrides and embedding the effective values in every report. Reject unknown or contradictory registry values with stable diagnostics instead of silently changing project counts.",
            "- [ ] Add a dependency-universe contract so a project-filtered report can evaluate permitted cross-project/cross-file dependencies without exposing unrelated ticket bodies. Preserve `dependency_unknown` when the referenced ticket is missing, unreadable, private, archived outside scope, or rejected by workspace resolution, and disclose the reason without guessing its state.",
            "- [ ] Register `ticket-project-report-v1.schema.json` in the schema bundle/index and capability discovery, add schema compatibility fixtures, and extend the report with version/sprint attention only after authoritative `record:version` and `record:sprint` contracts exist.",
        ])
        seen.add("ticket metrics")
        replaced = True
    if not replaced:
        output.append(line)

expected = set(replacements) | {"ticket metrics"}
missing = sorted(expected - seen)
if missing:
    raise SystemExit("todo.md prefixes not found: %s" % ", ".join(missing))
path.write_text("\n".join(output) + "\n", encoding="utf-8")
